### PR TITLE
Reported the status as deleted for the deleted resources in crossplane beta trace

### LINKED ISSUE #5363: Don't report error status for deleted resources in crossplane beta trace
When running `crossplane beta trace` on a claim/composite that is in the process if being deleted, the resource status for all of the "missing" resources reports as `Error: foo not found`

### How could Crossplane help solve your problem?

It would be more readable/logical for the code to detect the fact that the Composite is being deleted and report the status as `Deleted` for the sub-resources that no longer exist.

### PR DESCRIPTION
**Pull request by NeerajNagure**
### Description of your changes
When running `crossplane beta trace` on a claim/composite that is in the process if being deleted, the resource status for all of the "missing" resources is now reported as "Deleted"

Fixes #5363 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: cmd/crank/beta/trace/internal/printer/default.go [hunk 1]
```diff
@@ -216,6 +216,9 @@ func getResourceStatus(r *resource.Resource, name string, wide bool) fmt.Stringe
 	syncedCond := r.GetCondition(xpv1.TypeSynced)
 	var status, m string
 	switch {
+	case r.Unstructured.GetDeletionTimestamp() != nil:
+		// Report the status as deleted if the resource is being deleted
+		status = "Deleted"
```
Comment (negz) [inline cmd/crank/beta/trace/internal/printer/default.go:221]: Maybe `Deleting`? The resource still existing implies something is still processing the delete.

**Review by negz — APPROVED** [review]
With the caveat that I don't know this command's implementation very well this LGTM.

File: cmd/crank/beta/trace/internal/printer/default.go (hunk 1 above)
Comment (NeerajNagure) [reply cmd/crank/beta/trace/internal/printer/default.go]: made the changes

**Comment by NeerajNagure** [comment]
@negz I have changed the status to deleting. Please take a look.

**Review by phisco — APPROVED** [review]
