### PR TITLE
Fix CRD-to-MRD converter to preserve provider configuration CRDs

### LINKED ISSUE #6719: CRD-to-MRD converter converts provider configuration types to MRDs
### What happened?

The CRD-to-MRD converter converts provider configuration CRDs to MRDs. Provider types like `ProviderConfig`, `ClusterProviderConfig`, and `ProviderConfigUsage` are not managed resources - they're provider configuration and lifecycle management types that should remain as regular CRDs.

https://github.com/crossplane/crossplane/blob/a86bdf1/internal/converter/custom_to_managed.go#L48

The converter currently converts all CustomResourceDefinitions based on GroupVersionKind without distinguishing between managed resources and provider configuration types.

When installing `provider-aws-s3:v2.0.0` (which depends on `provider-family-aws:v2.0.0`), these types get converted to inactive MRDs:

```
clusterproviderconfigs.aws.m.upbound.io                        Inactive   False
providerconfigs.aws.m.upbound.io                               Inactive   False
providerconfigs.aws.upbound.io                                 Inactive   False
providerconfigusages.aws.m.upbound.io                          Inactive   False
providerconfigusages.aws.upbound.io                            Inactive   False
```

Since there's no default MRAP, no actual CRDs get created. `kubectl api-resources` shows no ProviderConfig types are available, making it impossible to configure provider authentication without creating an MRAP first.

### What did you expect to happen?

Provider configuration types should be excluded from CRD-to-MRD conversion and remain as regular CRDs that get installed immediately, regardless of MRAPs.

The converter should identify and skip conversion for:
- `ProviderConfig` (both `.m.` and legacy versions)
- `ClusterProviderConfig` 
- `ProviderConfigUsage` (both `.m.` and legacy versions)

After provider installation, `kubectl api-resources` should show ProviderConfig types are available for immediate use.

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Fixes #6719

The CRD-to-MRD converter was converting all CRDs to MRDs, including provider configuration types like `ProviderConfig`, `ClusterProviderConfig`, and `ProviderConfigUsage`. These are not managed resources and should remain as regular CRDs that get installed immediately.

This PR updates the converter to use `isManagedResource()` to identify which CRDs represent actual managed resources. Provider configuration types are excluded from conversion and remain as regular CRDs in the output.

The converter function is renamed from `mrdObjs` to `converted` and documentation is updated to clarify that the output contains a mix of MRDs and unchanged CRDs, not only MRDs.

**Migration:** This change affects provider configuration CRDs that were converted to MRDs instead of remaining as regular CRDs. While we generally avoid potentially breaking changes, we're taking this approach here due to very specific circumstances: MRD-supporting providers were first published today (v2.0.0 released Friday), creating an extremely narrow window of potential impact. Building migration logic would add complexity for what is likely a very small number of affected installations. For users who installed providers between v2.0.0's release and this fix, reinstalling the provider will resolve the issue.

**Testing:**
Verified with `earthly +hack --SIMULATE_CROSSPLANE_VERSION=v2.0.1` and `provider-aws-s3:v2.0.0`:

**Before:**
```bash
$ kubectl get crd | grep providerconfig
# No output - ProviderConfig CRDs were converted to inactive MRDs

$ kubectl api-resources | grep providerconfig  
# No output - ProviderConfig APIs unavailable
```

**After:**
```bash
$ kubectl get crd | grep providerconfig
clusterproviderconfigs.aws.m.upbound.io    2025-08-12T19:41:45Z
providerconfigs.aws.m.upbound.io           2025-08-12T19:41:45Z
providerconfigs.aws.upbound.io             2025-08-12T19:41:45Z
providerconfigusages.aws.m.upbound.io      2025-08-12T19:41:45Z
providerconfigusages.aws.upbound.io        2025-08-12T19:41:45Z

$ kubectl api-resources | grep providerconfig
clusterproviderconfigs               aws.m.upbound.io/v1beta1    false    ClusterProviderConfig
providerconfigs                      aws.m.upbound.io/v1beta1    true     ProviderConfig
# ... etc - All ProviderConfig APIs immediately available
```

S3 managed resources are still correctly converted to inactive MRDs requiring MRAP activation.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~ (unit tests cover the conversion logic)
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~ (internal bug fix)
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~ (v2.0 specific feature)
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~ (no API changes)

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: internal/converter/custom_to_managed.go [hunk 1]
```diff
@@ -81,6 +100,25 @@ func CustomToManagedResourceDefinitions(defaultActive bool, objects ...runtime.O
...
+// other non-managed resource types.
+func isManagedResource(crd map[string]any) bool {
+	paved := fieldpath.Pave(crd)
+	
+	kind, err := paved.GetString("spec.names.kind")
+	if err != nil {
+		return true // Default to treating as managed resource if kind cannot be retrieved
+	}
+	
+	switch kind {
```
Comment (n3wscott) [inline internal/converter/custom_to_managed.go:114]: Only checking Kind and not checking ApiVersion allows someone to namesquat one of these kinds and bypass the activation policy

Comment (negz) [reply internal/converter/custom_to_managed.go:114]: True. How realistic is that concern in practice though?

Would we expect a malicious provider to do this? What would they gain? I imagine the more likely scenario is that someone accidentally names an MR kind 'ProviderConfig', conflicting with Crossplane's 'reserved' (by convention) type of the same kind. We've had this type for ~7 years and I haven't seen that happen yet, so I'm not super worried about it.

That all said, I would check the API version as well if there was a straightforward way to do so. The challenge is we don't know what it'll be. The kind is always `ProviderConfig`, but the group might be `aws.m.crossplane.io`, `gcp.m.crossplane.io`, `internal.example.org`, etc etc.

**Review by jbw976 — APPROVED** [review]
Thanks for this fix @negz!
