### PR TITLE
fix(functions): unique field owners to prevent hijacking composed resources

### LINKED ISSUE #5035: Composition doesn't check composed resource's owner with functions
### What happened?

Functions spec allows setting a `metadata.name` for composed resources (`SHOULD NOT`), which could if not handled with care lead to multiple composite resources applying the same managed resource repeatedly.

### How can we reproduce it?

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.0
  ignoreCrossplaneConstraints: true
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.2.2
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xusers.example.org
spec:
  group: example.org
  names:
    kind: XUser
    plural: xusers
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            someinput:
              type: string
            someotherinput:
              type: string
        status:
          type: object
          properties:
            coolField:
              type: string
            coolerField:
              type: string
```
then applying the following composition:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xuser-test-nopresource
spec:
  compositeTypeRef:
    apiVersion: example.org/v1
    kind: XUser
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: nop.crossplane.io/v1alpha1
            kind: NopResource
            metadata:
              name: "test" # <= hardcoded name
              annotations:
                "gotemplating.fn.crossplane.io/composition-resource-name": "test"
            spec:
             forProvider:
              conditionAfter:
              - conditionType: Ready
                conditionStatus: "False"
                time: 0s
              - conditionType: Ready
                conditionStatus: "True"
                time: 1s
              fields:
               parent: {{ .observed.composite.resource.metadata.name }}
               {{ with .observed.composite.resource.spec.someinput }}
               someinput: {{ . }}
               {{ end }}
               {{ with .observed.composite.resource.spec.someotherinput }}
               someotherinput: {{ . }}
               {{ end }}
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
```
and two XRs:
```yaml
---
apiVersion: example.org/v1
kind: XUser
metadata:
  name: example-xuser-1
spec:
  someinput: "True"
  compositionRef:
    name: xuser-test-nopresource
---
apiVersion: example.org/v1
kind: XUser
metadata:
  name: example-xuser-2
  labels:
    something: "True"
spec:
  someotherinput: "True"
  compositionRef:
    name: xuser-test-nopresource
```

You can see NopResource flaps between the two indefinitely:
```
$ kubectl get nopresources.nop.crossplane.io -o yaml test --show-managed-fields -w
...
---
apiVersion: nop.crossplane.io/v1alpha1
kind: NopResource
metadata:
  annotations:
    crossplane.io/composition-resource-name: test
    crossplane.io/external-name: test
  creationTimestamp: "2023-11-17T14:38:35Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: example-xuser-2-
  generation: 22
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: example-xuser-2
  managedFields:
  - apiVersion: nop.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/composition-resource-name: {}
        f:generateName: {}
        f:labels:
          f:crossplane.io/claim-name: {}
          f:crossplane.io/claim-namespace: {}
          f:crossplane.io/composite: {}
        f:ownerReferences:
          k:{"uid":"be6f7c51-3199-4a6e-b856-1ad394efdeeb"}: {}
      f:spec:
        f:forProvider:
          f:conditionAfter: {}
          f:fields:
            f:parent: {}
            f:someotherinput: {}
    manager: apiextensions.crossplane.io/composed
    operation: Apply
    time: "2023-11-17T14:48:25Z"
  - apiVersion: nop.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-name: {}
        f:finalizers:
          .: {}
          v:"finalizer.managedresource.crossplane.io": {}
    manager: provider-nop
    operation: Update
    time: "2023-11-17T14:38:35Z"
  - apiVersion: nop.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:atProvider: {}
        f:conditions: {}
    manager: provider-nop
    operation: Update
    subresource: status
    time: "2023-11-17T14:38:36Z"
  name: test
  ownerReferences:
  - apiVersion: example.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: XUser
    name: example-xuser-2
    uid: be6f7c51-3199-4a6e-b856-1ad394efdeeb
  resourceVersion: "4014"
  uid: 21e58452-b632-4885-9462-d68aeea750c4
spec:
  deletionPolicy: Delete
  forProvider:
    conditionAfter:
    - conditionStatus: "False"
      conditionType: Ready
      time: 0s
    - conditionStatus: "True"
      conditionType: Ready
      time: 1s
    fields:
      parent: example-xuser-2
      someotherinput: true
  providerConfigRef:
    name: default
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-11-17T14:38:35Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-11-17T14:38:36Z"
    reason: ""
    status: "True"
    type: Ready
---
apiVersion: nop.crossplane.io/v1alpha1
kind: NopResource
metadata:
  annotations:
    crossplane.io/composition-resource-name: test
    crossplane.io/external-name: test
  creationTimestamp: "2023-11-17T14:38:35Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: example-xuser-1-
  generation: 23
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: example-xuser-1
  managedFields:
  - apiVersion: nop.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/composition-resource-name: {}
        f:generateName: {}
        f:labels:
          f:crossplane.io/claim-name: {}
          f:crossplane.io/claim-namespace: {}
          f:crossplane.io/composite: {}
        f:ownerReferences:
          k:{"uid":"9b65b33f-f92f-4412-9384-3e52acaa5a72"}: {}
      f:spec:
        f:forProvider:
          f:conditionAfter: {}
          f:fields:
            f:parent: {}
            f:someinput: {}
    manager: apiextensions.crossplane.io/composed
    operation: Apply
    time: "2023-11-17T14:48:50Z"
  - apiVersion: nop.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-name: {}
        f:finalizers:
          .: {}
          v:"finalizer.managedresource.crossplane.io": {}
    manager: provider-nop
    operation: Update
    time: "2023-11-17T14:38:35Z"
  - apiVersion: nop.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:atProvider: {}
        f:conditions: {}
    manager: provider-nop
    operation: Update
    subresource: status
    time: "2023-11-17T14:38:36Z"
  name: test
  ownerReferences:
  - apiVersion: example.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: XUser
    name: example-xuser-1
    uid: 9b65b33f-f92f-4412-9384-3e52acaa5a72
  resourceVersion: "4072"
  uid: 21e58452-b632-4885-9462-d68aeea750c4
spec:
  deletionPolicy: Delete
  forProvider:
    conditionAfter:
    - conditionStatus: "False"
      conditionType: Ready
      time: 0s
    - conditionStatus: "True"
      conditionType: Ready
      time: 1s
    fields:
      parent: example-xuser-1
      someinput: true
  providerConfigRef:
    name: default
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-11-17T14:38:35Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-11-17T14:38:36Z"
    reason: ""
    status: "True"
    type: Ready
```

### What environment did it happen in?
Crossplane version: using master, but applies to 1.14 too

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/5035

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 1]
```diff
@@ -408,7 +410,10 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 		// Specifically it will merge rather than replace owner references (e.g.
 		// for Usages), and will fail if we try to add a controller reference to
 		// a resource that already has a different one.
-		if err := c.client.Patch(ctx, cd.Resource, client.Apply, client.ForceOwnership, client.FieldOwner(FieldOwnerComposed)); err != nil {
+		// NOTE(phisco): We need to set a field owner unique for each XR here,
+		// this prevents multiple XRs composing the same resource to be
+		// continuously alternated as controllers.
+		if err := c.client.Patch(ctx, cd.Resource, client.Apply, client.ForceOwnership, client.FieldOwner(xr.GetName())); err != nil {
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:416]: Would it make sense to prefix the XR name with `FieldOwnerComposed`? Assuming there's no length issues it might make identifying field owners easier.

File: internal/controller/apiextensions/composite/reconciler.go [hunk 2]
```diff
@@ -595,6 +596,12 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
 		}
 		err = errors.Wrap(err, errCompose)
 		r.record.Event(xr, event.Warning(reasonCompose, err))
+		if kerrors.IsInvalid(err) {
+			// invalid errors could be unstable due to pointers in the error
+			// message, so we just log them, but avoid setting them as
+			// condition, to avoid endlessly looping.
+			err = errors.Wrap(errors.New(errInvalidResources), errCompose)
+		}
```
Comment (negz) [inline internal/controller/apiextensions/composite/reconciler.go:604]: I don't understand this bit. Could you elaborate? What would cause us to endlessly loop?

Comment (phisco) [reply internal/controller/apiextensions/composite/reconciler.go:604]: In this specific case the Invalid error returned by the API server contains the full fmt representation of the invalid part of the resource (`ownerRefs`) which is unstable due to it containing pointers to bools that are different at every reconciliation. This means we update the XR condition with a new error every time and therefore trigger a new reconciliation loop every time.

https://github.com/crossplane/crossplane/pull/4918 would have prevented that too.

Comment (negz) [reply internal/controller/apiextensions/composite/reconciler.go:604]: Got it, thanks.

It's obvious to me in retrospect but explicitly mentioning that it's the API server returning unstable error strings might help.

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 1 above)
Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: @phisco FYI this is the only thing blocking me approving.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: Sorry missed it, I'll double-check there is no length limit and add that if not.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: should be at most 128 characters:
image

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: which is much shorter than the 253 allowed characters for names 🤔 we should either crop it or hash it actually.

Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: Could we use the XR's UID? `FieldOwnerComposed-<36 chars>` should fit.

The only issue I can think of would be if we wanted to backup and restore the XR and all of its composed resources. The restored XR would have a new UID.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: I'm not sure whether we would preserve managed fields restoring 🤔 however, what we want to avoid at all costs is collisions, ownership is already clearly stated in the ownerRefs, so the prefix + UID or hash could be both fine, but the hash would be stable w.r.t. the name, so there would be no risk at all of issues at restore time, while the UID could potentially cause some.

Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: Yeah my guess is that UID might be a non-starter. CC resident backup-and-restore expert @turkenh.

Hash of the name SGTM, ideally with some human readable prefix.

Comment (turkenh) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: > I'm not sure whether we would preserve managed fields restoring

No, we don't. UIDs change after backup/restore. 
+1 for hashing the name.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:416]: 🤔 @negz @turkenh, should I also include the GVK in the hash? I feel it could cause some issues in case of version bumps of the XR, so the version should not definitely be hashed, but what about the group and kind? is there any possible scenario where a user is willingly changing the XR of a set of composed resources altogether, except for the name?

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go]: have a look at 
https://github.com/crossplane/crossplane/pull/5236/commits/687bf3eb3a4d8a293e8acb7abbfd78f7c5b8487f

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 3]
```diff
@@ -418,6 +425,29 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
...
+// don't have one), or version (to allow version changes without needing to
+// update the field owner name).
+//
+// We decided to include the GK in the hash to prevent transferring ownership of
+// composed resources across XRs with whole new GK, as that should not be
+// supported without manual intervention.
+//
+// Given that field owner names are limited to 128 characters, the function
+// truncates the hash to 32 characters. A longer hash was deemed unnecessary.
+func getComposedFieldOwnerName(xr *composite.Unstructured) string {
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:445]:
```suggestion
func ComposedFieldOwner(xr *composite.Unstructured) string {
```

Nit: Just to make it a little more succinct.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 4]
```diff
@@ -418,6 +425,29 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
...
+// does not include the XR's UID (as it's not deterministic), namespace (XRs
+// don't have one), or version (to allow version changes without needing to
+// update the field owner name).
+//
+// We decided to include the GK in the hash to prevent transferring ownership of
+// composed resources across XRs with whole new GK, as that should not be
+// supported without manual intervention.
+//
+// Given that field owner names are limited to 128 characters, the function
+// truncates the hash to 32 characters. A longer hash was deemed unnecessary.
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:444]: How did you land at 32 chars? Could be worth including a little more detail.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:444]: No particular reason, I could have done the actual math and made it exactly 128 chars with the prefix, but I felt that was overkill and 32 characters were more than enough to avoid collisions.

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 1 above)
Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go]: I _think_ that approach SGTM.

The only thing I'm wondering is whether we're thinking about field owners and controller references the right way.

[The SSA docs](https://kubernetes.io/docs/reference/kubernetes-api/common-parameters/common-parameters/#fieldManager) say the field manager (aka owner) should be "the actor or entity that is making the changes". I can't find clear guidance, but for a child resource produced by a controller I'd intuitively consider the actor to be the controller doing the reconciling, not the parent resource being reconciled.

XR controllers are GVK-scoped. One XR controller owns and reconciles all XRs of a particular GVK. You're right that the version could change over time, so let's say they're GK scoped. I'd therefore expect that the field manager would be `apiextensions.crossplane.io/composite/example.org/Widget` - without a name. It certainly doesn't seem like the `fieldManager` field was _designed_ to fit enough information to uniquely identify a resource, unless they were expecting us to use a UID?

[The controller reference design doc](https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/controller-ref.md) seems to support this expectation. It states that the main goal of a controller reference is to solve the problem of controllers that fight over controlled objects. It uses two _different_ controllers - ReplicaSet and ReplicationController - to illustrate this example.

On the other hand, a controller reference is a reference to a specific resource, not just a controller. We've certainly always used controller references to ensure one parent resource does not accidentally adopt a child that belongs to another parent of the same type, with the same controller.

I also can't see how it would be possible to write a truly [reconstructive controller](https://kubernetes.io/blog/2022/10/20/advanced-server-side-apply/#reconstructive-controllers) without uniquely identifying the parent resource as the field manager. If you use only the controller as the field manager, the controller would always need to read a composed resource and check its controller reference before applying desired state. Otherwise SSA would allow two XRs of the same kind (reconciled by the same controller) to fight over control for the same composed resource.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 5]
```diff
@@ -418,6 +425,29 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
...
+func getComposedFieldOwnerName(xr *composite.Unstructured) string {
+	h := sha256.New()
+	_, _ = fmt.Fprintf(h, "%s-%s", xr.GetName(), xr.GroupVersionKind().GroupKind())
+	return FieldOwnerComposedPrefix + "-" + hex.EncodeToString(h.Sum(nil))[:32]
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:448]:
```suggestion
	return FieldOwnerComposedPrefix + "/" + hex.EncodeToString(h.Sum(nil))[:32]
```

Nit. This way there's a consistent separator character - `apiextensions.crossplane.io/composite/hashhashhash`.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 6]
```diff
@@ -418,6 +425,29 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
...
+//
+// We decided to include the GK in the hash to prevent transferring ownership of
+// composed resources across XRs with whole new GK, as that should not be
+// supported without manual intervention.
+//
+// Given that field owner names are limited to 128 characters, the function
+// truncates the hash to 32 characters. A longer hash was deemed unnecessary.
+func getComposedFieldOwnerName(xr *composite.Unstructured) string {
+	h := sha256.New()
+	_, _ = fmt.Fprintf(h, "%s-%s", xr.GetName(), xr.GroupVersionKind().GroupKind())
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:447]:
```suggestion
	_, _ = h.Write([]byte(xr.GetName() + xr.GroupVersionKind().GroupKind()))
```

Nit: I don't think the `-` separator is needed here given we'll one-way hash it.

**Comment by negz** [comment]
@phisco Will this break folks who upgrade? I don't think so, right? I'm guessing SSA will allow the field owner to change because we're forcing it, and not changing the controller reference.

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 1 above)
Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go]: Yes, it is odd indeed. Looks like the assumption is that a specific controller is only going to reconcile a resource for a single reason, hence a single name per controller is enough, while in our case the same XR controller could be reconciling the same composed resource for multiple XRs, hence we need a unique name for each XR to allow SSA to properly prevent hijackings.

**Comment by phisco** [comment]
Yes, exactly, the only scenario I can think of where this could could cause some issue is if at the same time as the field owner change for some reason the applied resource specification shrinked (as in: before it was setting `spec.foo` and then it's not), which would mean a subset of the old configuration applied would continue being owned by the old field manager instead of being unset. But I don't think it's a huge risk.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 7]
```diff
@@ -418,6 +425,29 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
...
+// The function `getComposedFieldOwnerName` generates a unique field owner name
+// for a given Crossplane composite resource (XR). This uniqueness is crucial to
+// prevent multiple XRs, which compose the same resource, from continuously
+// alternating as controllers.
+//
+// The function generates a deterministic hash based on the XR's name and
+// GroupKind (GK), ensuring consistency even during system restores. The hash
+// does not include the XR's UID (as it's not deterministic), namespace (XRs
+// don't have one), or version (to allow version changes without needing to
+// update the field owner name).
```
Comment (jpbetz) [inline internal/controller/apiextensions/composite/composition_functions.go:437]: If the XR is deleted and another is created with the same name, what is the desired behavior?  Is it guaranteed to be owned by the same field manager or is the new object lifecycle possibly owned by a different field manager?

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:437]: yeah, that would be the worst scenario, ideally we would like to have the old resource being deleted and a new one created, but if the deletion happens in background that is not guaranteed and if a new resource with the same name is created in the meantime, it could become the owner of the resource and happily switch the ownerRef without complaining because the field manager is the same. Which is exactly what happens today already. We would need to use a unique name for the specific XR to avoid that, right?

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 8]
```diff
@@ -498,6 +505,29 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
...
+// We decided to include the GK in the hash to prevent transferring ownership of
+// composed resources across XRs with whole new GK, as that should not be
+// supported without manual intervention.
+//
+// Given that field owner names are limited to 128 characters, the function
+// truncates the hash to 32 characters. A longer hash was deemed unnecessary.
+func ComposedFieldOwnerName(xr *composite.Unstructured) string {
+	h := sha256.New()
+	_, _ = h.Write([]byte(xr.GetName() + xr.GroupVersionKind().GroupKind().String()))
+	return FieldOwnerComposedPrefix + "/" + hex.EncodeToString(h.Sum(nil))[:32]
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:528]:
```suggestion
	return fmt.Sprintf("%s/%x", FieldOwnerComposedPrefix, h.Sum(nil))
```

FWIW if you don't truncate the hash at all the field owner will always fit. It will always be 101 characters, vs 69 when truncated. See https://go.dev/play/p/kTU-b-C67MK for example.

I don't feel strongly either way. The shorter hash is unlikely to collide assuming tens of thousands of XRs in a control plane, and looks a little better readability wise. On the other hand the longer hash will always fit, and gives us even more collision resistance. 🤷‍♂️

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 4 above)
Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:524]: See comment below.

**Review by negz — APPROVED** [review]

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 8 above)
Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go]: went with this 👍
