### PR TITLE
Fix: enforcedCompositonRef change requires pod restart

### LINKED ISSUE #6230: `enforcedCompositionRef` conflicting with Claim/Composite sync
### What happened?

We are starting using the `enforcedCompositionRef` feature to migrate from a multiple-composition-per-API to a one-compoistion-per-API setup.

While testing we found to 2 major problems with the behaviour of that parameter:

1. after updating an XRD with added  `enforcedCompositionRef`, this only takes effect after a Crossplane Pod restart
2. the Claim/Composite sync (CSA, not tested with SSA alpha feature) is conflicting with `enforcedCompositionRef`  for the setting of `compositionRef`.
   * this results in Claims/Composites with this:
      ```
      spec:
        claimRef:
          apiVersion: cluster/v1alpha1
          kind: NodePool
          name: tenant-nodepool
          namespace: tenant
        compositionRef:
          name: node-pool-iat
        compositionRevisionRef:
          name: node-pool-34014e3
        compositionSelector:
          matchLabels:
            stage: iat
        compositionUpdatePolicy: Automatic
      ``` 
   * in the events of the XR we see the CompositionSelection-loop (increasing loop interval) :
      ```
      Events:
        Type    Reason                Age                From                                                             Message
        ----    ------                ----               ----                                                             -------
        Normal  CompositionSelection  17m (x2 over 53m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Enforced composition has been selected
        Normal  ComposeResources      9m18s              defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully composed resources
      ```
   * sometimes (e.g. in k9s) you can catch the flicker where shortly `compositionRef` has the desired Composition name
   * however the `compositionRevisionRef` seems to never change.
   * also it is possible to delete the old Composition (here "node-pool-iat"), because none of its CompositionRevision is in use
   * Note: in cases/APIs where there is only a Composite (no Claim, e.g. composed via other Composition), we do not see this behaviour 

### How can we reproduce it?

1. base setup: 
   * XRD (without `enforcedCompositionRef`)
   * 2 Compositions (A + B) for that API
   * 1 deployed test Claim that references composition A (directly `compositionRef` or via `compositionSelector`)
2. update the XRD with an enforcedCompositionRef for composition B
3. trigger manually (or wait) for Crossplane Pod restart
4. look at XRC/XR spec and XR Events (as seen in the examples above)

### What environment did it happen in?
Crossplane version: 1.17.1

### PR DESCRIPTION
**Pull request by ezgidemirel**
### Description of your changes

The `EnforcedCompositionSelector` was caching the `CompositeResourceDefinition` (XRD) object at initialization time, which meant that changes to the `enforcedCompositionRef` field wouldn't be picked up without restarting the Crossplane pod. This change fixes this behavior by fetching the XRD dynamically on each reconcile.

Fixes #6230

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [x] Added `backport release-x.y` labels to auto-backport this PR.
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: internal/controller/apiextensions/composite/api.go [hunk 1]
```diff
@@ -327,32 +327,34 @@ func (s *APIDefaultCompositionSelector) SelectComposition(ctx context.Context, c
 }
 
 // NewEnforcedCompositionSelector returns a EnforcedCompositionSelector.
-func NewEnforcedCompositionSelector(def v1.CompositeResourceDefinition, r event.Recorder) *EnforcedCompositionSelector {
-	return &EnforcedCompositionSelector{def: def, recorder: r}
+func NewEnforcedCompositionSelector(c client.Client, defRef corev1.ObjectReference, r event.Recorder) *EnforcedCompositionSelector {
```
Comment (phisco) [inline internal/controller/apiextensions/composite/api.go:330]: nit: `defRef` took me a while to decypher, `xrdRef` maybe would be more explicit

Comment (ezgidemirel) [reply internal/controller/apiextensions/composite/api.go:330]: I also prefer `xrd` over `def` but the rest of the file uses `def` for compositeResourceDefinition

File: internal/controller/apiextensions/composite/api.go [hunk 2]
```diff
@@ -327,32 +327,34 @@ func (s *APIDefaultCompositionSelector) SelectComposition(ctx context.Context, c
...
-	def      v1.CompositeResourceDefinition
+	client   client.Client
+	defRef   corev1.ObjectReference
 	recorder event.Recorder
 }
 
 // SelectComposition selects the enforced composition if it's given in definition.
-func (s *EnforcedCompositionSelector) SelectComposition(_ context.Context, cp resource.Composite) error {
-	// We don't need to fetch the CompositeResourceDefinition at every reconcile
-	// because enforced composition ref is immutable as opposed to default
```
Comment (jbw976) [inline internal/controller/apiextensions/composite/api.go:344]: according to the XRD type definition, this value should be immutable. Any reason why that seems to not be the case in reality? e.g. @ezgidemirel repro steps in https://github.com/crossplane/crossplane/issues/6230#issuecomment-3145035363 update this field on the XRD with no problems.

* v1: https://github.com/crossplane/crossplane/blob/main/apis/apiextensions/v1/xrd_types.go#L102
* v2: https://github.com/crossplane/crossplane/blob/main/apis/apiextensions/v2/xrd_types.go#L70

**Review by jbw976 — COMMENTED** [review]
I have a bit of confusion about why the immutability is not being enforced, any insight there? 🤔

File: internal/controller/apiextensions/composite/api.go (hunk 2 above)
Comment (ezgidemirel) [reply internal/controller/apiextensions/composite/api.go:344]: @jbw976 , once the field is set to a value, it's immutable. I confirmed that changing the enforced composition is not possible without deleting and recreating the XRD.
