### PR TITLE
fix(environmentConfigs): revert to v1alpha1 as storageversion to fix rollback issues

### LINKED ISSUE #6148: Recent Crossplane version downgrades not working
### What happened?

Currently both `1.18` -> `1.17` and `1.17` -> `1.16` not working, see below. I am not sure if there are further errors to be revealed, but both errors are due to bumping storageVersion while bumping the apiVersion, for example, we bump `EnvironmentConfig` from `v1alpha1` to `1beta1` and mark the new one as the storageVersion. This is fine but when we attempt downgrading to previous version, applying CRD for `EnvironmentConfig` `v1beta1` fails since kube complains about storageVersion (`v1beta1`) not being around.

To avoid this problem, while bumping the api versions, we could have keep the old versions as storageVersion, but that would mean every resource with the new version being converted from v1beta1 -> v1alpha1 whenever stored and v1alpha1 -> v1beta1 whenever it is served/accessed from the storage.

```
# on a fresh cluster, install XP 1.18.1
❯ helm upgrade --install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane
# downgrade it to XP 1.17.3
❯ helm upgrade --install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane --version 1.17.3

❯ kubectl -n crossplane-system get pods -w
NAME                                       READY   STATUS                  RESTARTS     AGE
crossplane-6b8546d66d-dw5kc                1/1     Running                 0            49s
crossplane-6f8565c574-g95d9                0/1     Init:CrashLoopBackOff   1 (5s ago)   15s
crossplane-rbac-manager-7d8c56f6f4-8859t   1/1     Running                 0            15s

❯ kubectl -n crossplane-system logs -f crossplane-6f8565c574-g95d9 -c crossplane-init
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"TLS CA secret is complete.","Step":"TLSCertificateGenerator"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"TLS secret contains server certificate.","Step":"TLSCertificateGenerator","secret":"crossplane-tls-server"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"TLS secret contains client certificate.","Step":"TLSCertificateGenerator","secret":"crossplane-tls-client"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"Step has been completed","Name":"TLSCertificateGenerator"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-12-02T06:10:45Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
crossplane: error: cannot initialize core: cannot apply crd: cannot patch object: CustomResourceDefinition.apiextensions.k8s.io "environmentconfigs.apiextensions.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta1": must appear in spec.versions
```

```
# on a fresh cluster, install XP 1.17.3
❯ helm upgrade --install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane --version 1.17.3
# downgrade it to XP 1.16.4
❯ helm upgrade --install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane --version 1.16.4

❯ kubectl -n crossplane-system get pods -w
NAME                                       READY   STATUS                  RESTARTS     AGE
crossplane-68d895c96b-shnt4                0/1     Init:CrashLoopBackOff   1 (4s ago)   13s
crossplane-6f8565c574-h69dr                1/1     Running                 0            44s
crossplane-rbac-manager-78fd7d7986-wqld9   1/1     Running                 0            13s
^C%
❯ kubectl -n crossplane-system logs -f crossplane-68d895c96b-shnt4 -c crossplane-init
{"level":"info","ts":"2024-12-02T06:19:08Z","logger":"crossplane","msg":"TLS CA secret is complete.","Step":"TLSCertificateGenerator"}
{"level":"info","ts":"2024-12-02T06:19:08Z","logger":"crossplane","msg":"TLS secret contains server certificate.","Step":"TLSCertificateGenerator","secret":"crossplane-tls-server"}
{"level":"info","ts":"2024-12-02T06:19:08Z","logger":"crossplane","msg":"TLS secret contains client certificate.","Step":"TLSCertificateGenerator","secret":"crossplane-tls-client"}
{"level":"info","ts":"2024-12-02T06:19:08Z","logger":"crossplane","msg":"Step has been completed","Name":"TLSCertificateGenerator"}
{"level":"info","ts":"2024-12-02T06:19:08Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-12-02T06:19:08Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
crossplane: error: cannot initialize core: cannot apply crd: cannot patch object: CustomResourceDefinition.apiextensions.k8s.io "functionrevisions.pkg.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1": must appear in spec.versions
```

### What environment did it happen in?
Crossplane version: 1.18.1, 1.17.3, 1.16.4

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/6148

We introduced `v1beta1` and bumped the storage version in the same minor release, `1.18`, this means a user rolling back to the previous minor, `1.17`, hit the issue above due to `v1beta1` being used as storage version while trying to drop it, not being defined by the previous minor.

The generated code was copy of `v1beta1` type, dropping the `storageVersion` marker. This patch allows explicitly marking the copy and runs the migration for all existing `EnvironmentConfigs to `v1alpha1`. Next minor release (`1.19`) we'll bump the `storageVersion` to `v1beta1` and switch to migrate all existing `EnvironmentConfigs` to `v1beta1`, and we'll be able to drop `v1alpha1` in `1.20`. This way downgrades between minors should go smoothly, `1.20` -> `1.19` -> `1.18` -> `1.17`.

Manually tested by:
```bash
# spin up a kind cluster using this PR's code
$ earthly +hack
...
# create some EnvironmentConfigs
$ kubectl apply -f test/e2e/manifests/apiextensions/environment/default/setup/environmentConfigs.yaml
...
# downgrade to 1.17.3
$ helm upgrade --install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane --version 1.17.3

```

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [x] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet

### CODE REVIEW

File: apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go [hunk 1]
```diff
@@ -24,7 +24,9 @@ import (
 )
 
 // +kubebuilder:object:root=true
+// +kubebuilder:storageversion
 // +genclient
+// +kubebuilder:storageversion
```
Comment (jbw976) [inline apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go:29]: can you help me understand why there are two `+kubebuilder:storageversion` directives, and if their ordering/placement is meaningful? 😇

**Review by jbw976 — COMMENTED** [review]
I think this is making sense @phisco, thanks for trying to clean this up!

So for my own understanding, and perhaps a first attempt at documenting what the process should be here, is the below process correct?

* General approach
  * do not introduce a new CRD version and bump the storage version to it in the same release
  * always migrate to the storage version
  * we should open a series of tracking issues when we promote an API and assign them to upcoming milestones so the rest of the process is followed up on.
* `v1.0` introduce new API as `alpha`
  * `alpha`: storage, served
  * `beta`: not exist
* `v1.1`: introduce new `beta` version, but keep `storageVersion` as `alpha` and migrate all instances to old version `alpha` (important for downgrading from later versions)
  * `alpha`: storage, served
  * `beta`: served
* `v1.2`: bump `storageVersion` to new `beta` version, migrate all instances to new `beta` version
  * `alpha`: served
  * `beta`: storage, served
* `v1.3`: drop old `alpha` version entirely
  * `alpha`: not exist
  * `beta`: storage, served

**Comment by phisco** [comment]
I'd say you are right, yes.
I didn't think we would need the migration in `v1.1`, but we do, this way downgrade will work if you go .2 > .1 > .0, otherwise you'd get an error downgrading to .0 trying to remove the beta version while it's still used by some resources.

File: apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go (hunk 1 above)
Comment (phisco) [reply apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go:29]: Uhm, no, I think I modified the script and forgot to drop the old one

Comment (jbw976) [reply apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go:29]: ah okay 😅 - so one of these will be removed if you just run `make generate` again? 🤔

**Comment by jbw976** [comment]
btw @phisco I've opened the following tracking issues and assigned them to their appropriate milestones so we remember to follow up on the rest of this proposed long term migration plan 😉 

* https://github.com/crossplane/crossplane/issues/6162
* https://github.com/crossplane/crossplane/issues/6163

File: apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go (hunk 1 above)
Comment (phisco) [reply apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go]: Fixed, unfortunately there is a bit of guessing involved into appending the storage version marker in the right place. I missed a $ and the selector was matching both `genclient` and `genclient:nonNamespaced`. We should keep an eye on it when reviewing future PRs.

**Review by turkenh — APPROVED** [review]
LGTM. 

Per the plan, v1beta1 should be the storage on the main and this fix should only land on release-1.18. However, it makes sense to get the script changes on main, so, I assume we will bump storage version on main with a follow up PR..

**Comment by jbw976** [comment]
> I assume we will bump storage version on main with a follow up PR..

yep yep @turkenh, that's what https://github.com/crossplane/crossplane/issues/6162 is tracking. it's set for the v1.19 milestone, so we will follow up before the release!

* https://github.com/crossplane/crossplane/issues/6162
