### PR TITLE
Fix logger panic in dependency resolution and guard against future logger panic bugs

### LINKED ISSUE #3102: Invalid Package version causes XP to panic
### What happened?

Crossplane panics when trying to log about a lock issue:
```
1.6534635870410209e+09	DPANIC	crossplane	odd number of arguments passed as key-value pairs for logging	{"controller": "packages/lock.pkg.crossplane.io", "request": "/lock", "uid": "268a27ef-0551-4689-a769-4784e731e74b", "version": "126095196", "name": "lock", "ignored key": "dependency (xpkg.upbound.io/crossplane/provider-aws) does not have version in constraints (>=v0.27.0-0)"}
```

Crossplane had recently been upgraded from 1.6.x to 1.7.0. 
There was a single lock on the system that existed before XP was upgraded. 

```
apiVersion: v1
items:
- apiVersion: pkg.crossplane.io/v1beta1
  kind: Lock
  metadata:
    creationTimestamp: "2022-01-26T19:49:35Z"
    generation: 9873
    name: lock
    resourceVersion: "130572258"
    uid: 268a27ef-0551-4689-a769-4784e731e74b
kind: List
metadata:
  resourceVersion: ""

```

### How can we reproduce it?

Possibly upgrade Crossplane with a package lock that does not include a value version.

### What environment did it happen in?
Crossplane version: 1.7.0-up1.
K8s: EKS, v1.21.5-eks-9017834

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Fixes a panic in the logger when no version is supplied in the lock.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Updates all reconciler tests to use a test logger that mirrors
Crossplane's logger in debug mode. All logs are discarded, but passing
the logger will reveal any panics that result from any keys that are
passed without values.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

> Note: passing the logger in the reconciler tests should guard against these kind of bugs showing up in the future. We have had multiple instances where a log panic in debug mode has resulted in us needing to run a patch release, which is an unfortunate outcome that this will help avoid.

Fixes #3102 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Verified that all tests are passing successfully and that without the fix to the resolver reconciler test was failing with log panic.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by muvaf — APPROVED** [review]
LGTM!

File: internal/controller/apiextensions/composite/reconciler_test.go [hunk 1]
```diff
@@ -42,6 +45,7 @@ import (
 
 func TestReconcile(t *testing.T) {
 	errBoom := errors.New("boom")
+	testLog := logging.NewLogrLogger(zap.New(zap.UseDevMode(true), zap.WriteTo(io.Discard)).WithName("testlog"))
```
Comment (negz) [inline internal/controller/apiextensions/composite/reconciler_test.go:48]: Could be handy to define this in the logging package in future.

Comment (hasheddan) [reply internal/controller/apiextensions/composite/reconciler_test.go:48]: @negz agree 👍🏻 was planning on opening an issue on `crossplane-runtime`

Comment (negz) [reply internal/controller/apiextensions/composite/reconciler_test.go:48]: I forgot about this PR and was wondering why this pattern was everywhere. Definitely still feel like this would be good to have in crossplane-runtime. In fact we could probably make the NopLogger that everything uses by default use this pattern so that we'd detect panics without having to explicitly plumb it in everywhere.
