### PR TITLE
fix(environment): erroring if no matches in Single mode, configurable minMatch for Multiple

### LINKED ISSUE #5075: Select Required EnvironmentConfig doesnt work properly
### What happened?

Expectation: given Composition consumes at least 2 EnvironmentConfigs with resolution policy: Required. Second EnvCfg uses label selectors and might not be present when XR of the given Composition is created. Therefore no managed resource of XR of given Composition should be created unless all configs are fetched.

Currently: Composite with label selector doesnt wait for 2nd EnvCfg and creates managed resources that need only values from the 1st EnvCfg.

Why is this happening? 

[SelectEnvironment()](https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/reconciler.go#L567) constructs a list of references which are then fetched by [Fetch()](https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/reconciler.go#L575). In case of Refs, user inputs are just added to the list. in case of Selector, an empty list is returned if config with matching labels is not found.

### How can we reproduce it?

- Composition with 2 EnvironmentConfig sources
- both EnvCfg sources or at least the last one uses label selector
- environment resolution policy is required
- make only the 1st EnvCfg present in the environment and create a Claim

### What environment did it happen in?
Crossplane version: 1.14.2

### PR DESCRIPTION
**Pull request by P0t4T0o**
### Description of Fix

Fixes #5075 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] Added or updated e2e tests.
- [x] Linked a PR or a [docs tracking issue] to [document this change].
- [ ] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: internal/controller/apiextensions/composite/environment_selector.go [hunk 1]
```diff
@@ -87,7 +88,7 @@ func (s *APIEnvironmentSelector) SelectEnvironment(ctx context.Context, cr resou
 				s.buildEnvironmentConfigRefFromRef(src.Ref),
 			)
 		case v1.EnvironmentSourceTypeSelector:
-			ec, err := s.lookUpConfigs(ctx, cr, src.Selector.MatchLabels)
+			ec, err := s.lookUpConfigs(ctx, cr, src.Selector.MatchLabels, rev.Spec.Environment.IsRequired())
```
Comment (phisco) [inline internal/controller/apiextensions/composite/environment_selector.go:91]: nit: what about doing the check outside of the lookupConfigs method? just to avoid the additional bool parameter

File: internal/controller/apiextensions/composite/environment_selector.go [hunk 2]
```diff
@@ -38,6 +38,7 @@ const (
 	errFmtReferenceEnvironmentConfig   = "failed to build reference at index %d"
 	errFmtResolveLabelValue            = "failed to resolve value for label at index %d"
 	errListEnvironmentConfigs          = "failed to list environments"
+	errListEnvironmentConfigsNoResult  = "no EnvironmentConfig Found that matches labels"
```
Comment (phisco) [inline internal/controller/apiextensions/composite/environment_selector.go:41]:
```suggestion
	errListEnvironmentConfigsNoResult  = "no EnvironmentConfig found that matches labels"
```

**Comment by P0t4T0o** [comment]
> However, `spec.envirnment.policy.resolution/resolve` are at the root level, and should only influence how references are actually handled once defined. In case of label selection, it's tricky, as we need to actually list resources before "saving" them as references. So, wouldn't it make sense to change it according to the mode selected (`spec.environment.environmentConfigs[*].mode`), `Single` meaning exact 1, while `Multiple` meaning at most `maxMatch` (potentially adding a `minMatch` later on). WDYT @P0t4T0o?

Agree with you, as we discussed over slack, even though this would fix the issue and bring back the default behaviour, it is misusing resolution policy for the 2nd thing: construction of list of refs. What we really miss is a control over how many configs should be **at least** matched and put into the list of refs.
I like the idea of `minMatch` field as this would address the problem for `mode: Multiple` without much effort or changes. The single mode should already follow default behaviour:
```go
case v1.EnvironmentSourceSelectorSingleMode:
		switch len(cl.Items) {
		case 1:
			ec = append(ec, cl.Items[0])
		default:
			return nil, errors.Errorf(errFmtFoundMultipleInSingleMode, len(cl.Items))
		}
```
> I would still count it as a fix, as we didn't want to change the default behavior in the first place....

Since addition of `minMatch` shouldnt result in way too many changes than currently this PR brings. I can update the PR and add this field in following days. WDYT @phisco ?

**Comment by phisco** [comment]
Unfortunately, no matches don't result in an error even in `Single` mode as before the switch case you shared we are also checking the length of the array and exiting if it's 0 😅
I'd be fine adding `minMatch` as part of the fix, @P0t4T0o, no issue on my side, maybe we could keep the default (`nil`) to 0 though.

**Comment by P0t4T0o** [comment]
> Unfortunately, no matches don't result in an error even in `Single` mode as before the switch case you shared

ahh right, I checked the wrong function :D

File: apis/apiextensions/v1/composition_environment.go [hunk 3]
```diff
@@ -194,6 +194,10 @@ type EnvironmentSourceSelector struct {
 	// MaxMatch specifies the number of extracted EnvironmentConfigs in Multiple mode, extracts all if nil.
 	MaxMatch *uint64 `json:"maxMatch,omitempty"`
 
+	// MinMatch specifies the required minimum of extracted EnvironmentConfigs in Multiple mode.
+	// +kubebuilder:default=1
+	MinMatch uint64 `json:"minMatch,omitempty"`
```
Comment (phisco) [inline apis/apiextensions/v1/composition_environment.go:199]:
```suggestion
	MinMatch *uint64 `json:"minMatch,omitempty"`
```
Given that `minMatch` is not meant to be set in Single mode, would it be possible to keep it a pointer too, remove the default and expand the check we do for MaxMatch in EnvironmentSourceSelector.Validate method to also enforce this not being set in Single mode?

We do already have a few places where `nil` is handled as `1`, but in this case I'd make it mean `0`, just to avoid introducing a breaking change also for `Multiple` mode.

I think it's fine to have `Single` mode meaning "exactly" one match, while `Multiple` defaults to any number of matches, but can be constrained further if needed.

**Review by phisco — COMMENTED** [review]
The `resolve` policy `Required` is a little bit confusing, but technically as we discussed, is not about the behavior of these selectors, but rather what Crossplane should with the references only once they are set. So, what do you think about rewording the PR title to something like "fix(environment): erroring if no matches in Single mode, configurable minMatch for Multiple"?
