### PR TITLE
tests: AllOf failing immediately if fail-fast

### LINKED ISSUE #5672: e2e tests should fail fast
### What problem are you facing?

In our e2e test framework, is that it looks like a failure won't stop the rest of the checks from being performed, so the test continues after what should be a fatal failure.

For example, In `Assess("foo", funcs.AllOf(....` It seems reasonable to fail quickly if we've already detected a failed condition, instead of wasting more time on further checks that could take minute(s) each. 

In the [test output](https://github.com/crossplane/crossplane/actions/runs/8907369180/job/24461108624) copied for convenience below, we fail an assessment (`context deadline exceeded`) and then proceed to perform more checks like `Waiting 5m0s for...` and `Ensuring foo does not change within 1m0s....`.

```
feature.go:741: XNopResource.nop.example.org propagate-fields-removals-l2dkr doesn't yet have desired value at field path spec.parameters.tags[newtag]:   any(
        - 	s"NotFound",
        + 	string("v2"),
          )
    env.go:428: XR did not have desired value "NotFound" at field path spec.parameters.tags[newtag]: context deadline exceeded:

<ommitted>

    env.go:428: Ensuring claim NopResource.nop.example.org default/propagate-fields-removals does not change within 1m0s
    env.go:428: Claim NopResource.nop.example.org default/propagate-fields-removals did not change within 1m0s
    env.go:428: Waiting 5m0s for NopResource.nop.example.org default/propagate-fields-removals to have value "I'm cool!" at field path status.coolerField...
    env.go:428: 1 resources have desired value "I'm cool!" at field path status.coolerField after 0.506s
    env.go:428: Ensuring composite resource XNopResource.nop.example.org propagate-fields-removals-l2dkr does not change within 1m0s
    env.go:428: Composite resource XNopResource.nop.example.org propagate-fields-removals-l2dkr did not change within 1m0s
```

### How could Crossplane help solve your problem?

If an assessment fails in an e2e test then we should fail the entire test quickly.  Performing further checks after a failure isn't ideal because:

* it extends the running time of the test when we know the outcome isn't going to be successful
* it adds additional output to the test artifacts that makes it harder to find the original/actual failure

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

e2e-framework has its own fail-fast flag, see [docs](https://github.com/kubernetes-sigs/e2e-framework/tree/2135435d7f19b812bcce7963a6176a41ccc82755/examples/fail_fast). 

This makes `funcs.AllOf` aware of it, skipping the rest of the provided functions in fail-fast mode.

Fixes #5672.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: test/e2e/funcs/feature.go [hunk 1]
```diff
@@ -66,13 +66,18 @@ const DefaultPollInterval = time.Millisecond * 500
 
 type onSuccessHandler func(o k8s.Object)
 
-// AllOf runs the supplied functions in order.
+// AllOf runs the supplied functions in order. If a function fails the test and
+// the environment is configured to fail fast (e2e-framework's -fail-fast flag)
```
Comment (jbw976) [inline test/e2e/funcs/feature.go:70]: looks like we are specifying the intent to fail fast with `-test.failfast -fail-fast` in the e2e step https://github.com/crossplane/crossplane/blob/master/.github/workflows/ci.yml#L306C47-L306C72 - were you able to also verify that the flag is making it down into this testing context correctly?

**Review by jbw976 — APPROVED** [review]
Looks reasonable to me @phisco!! just a question about the flag from the gha workflows getting down into the test code...

File: test/e2e/funcs/feature.go (hunk 1 above)
Comment (phisco) [reply test/e2e/funcs/feature.go:70]: yes, in our specific case, we do build our [environment from the flags](https://github.com/crossplane/crossplane/blob/f626e8a530e2ecaecb7cd59633f0871836e4aa1c/test/e2e/main_test.go#L91), whether another user will pass down that correctly it's up to the user.
