### PR TITLE
Handle CronOperation and WatchOperation in alpha render op

### LINKED ISSUE #7020: crossplane alpha render op should support CronOperation and WatchOperation
### What problem are you facing?
`crossplane alpha render op` fails when run on `WatchOperation` and `CronOperation` manifests.

### How could Crossplane help solve your problem?
The render command should support converting `CronOperation` and `WatchOperation` manifests to `Operation` manifests.

### PR DESCRIPTION
**Pull request by bobh66**
### Description of your changes

Update `crossplane alpha render op` to accept `CronOperation` and `WatchOperation` manifests and extract
the `Operation` from the `operationTemplate`.

Fixes #7020

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `earthly +reviewable` to ensure this PR is ready for review.
- [X] Added or updated unit tests.
~- [ ] Added or updated e2e tests.~
~- [ ] Linked a PR or a [docs tracking issue] to [document this change].~
~- [ ] Added `backport release-x.y` labels to auto-backport this PR.~
-~ [ ] Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: cmd/crank/alpha/render/op/load.go [hunk 1]
```diff
@@ -41,7 +41,24 @@ func LoadOperation(fs afero.Fs, path string) (*opsv1alpha1.Operation, error) {
...
 		return op, nil
+	case opsv1alpha1.CronOperationGroupVersionKind:
+		cop := &opsv1alpha1.CronOperation{}
+		if err := yaml.Unmarshal(data, cop); err != nil {
+			return nil, errors.Wrapf(err, "cannot unmarshal operation from %q", path)
+		}
+		op.Kind = opsv1alpha1.OperationKind
+		op.Spec = cop.Spec.OperationTemplate.Spec
+		return op, nil
+	case opsv1alpha1.WatchOperationGroupVersionKind:
```
Comment (haarchri) [inline cmd/crank/alpha/render/op/load.go:55]: thanks @bobh66 for this enhancement i see its a Draft but i want to give some input here:

we missing here one piece for `WatchOperation` to work correctly: injecting the `RequiredResourceSelector` for the watched resource. 
Unlike `CronOperation` where we just use the template as-is, WatchOperation needs to:

- Identify the actual watched resource from the required resources input (my suggestion would be to mark the resource with annotation `ops.crossplane.io/watched-resource: "True"`)
- Create a `RequiredResourceSelector` with the actual resource's name and namespace (not placeholders)
- Inject this selector into each pipeline step's Requirements.RequiredResources 

so something like this will work:

```go
	case v1alpha1.WatchOperationGroupVersionKind:
		// Parse as WatchOperation and extract the template
		var watchOp v1alpha1.WatchOperation
		if err := kyaml.Unmarshal(data, &watchOp); err != nil {
			return nil, errors.Wrapf(err, "cannot unmarshal WatchOperation from %q", path)
		}
		return newOperationFromWatchOperation(&watchOp, requiredResources)
```

```go
// newOperationFromWatchOperation creates a new Operation from a WatchOperation's template,
// injecting the watched resource selector into all pipeline steps.
func newOperationFromWatchOperation(wo *v1alpha1.WatchOperation, requiredResources []unstructured.Unstructured) (*v1alpha1.Operation, error) {
	// Find the watched resource (marked with annotation ops.crossplane.io/watched-resource: "True")
	var watched *unstructured.Unstructured
	for i := range requiredResources {
		res := &requiredResources[i]
		annotations := res.GetAnnotations()
		if annotations != nil && annotations[v1alpha1.RequirementNameWatchedResource] == "True" {
			watched = res
			break
		}
	}

	// If no watched resource found, return error
	if watched == nil {
		return nil, errors.New("no watched resource found in required resources - expected resource with annotation ops.crossplane.io/watched-resource: \"True\"")
	}

	// Build the selector for the watched resource
	sel := v1alpha1.RequiredResourceSelector{
		RequirementName: v1alpha1.RequirementNameWatchedResource,
		APIVersion:      watched.GetAPIVersion(),
		Kind:            watched.GetKind(),
		Name:            ptr.To(watched.GetName()),
	}
	if watched.GetNamespace() != "" {
		sel.Namespace = ptr.To(watched.GetNamespace())
	}

	// Create operation from template and inject selector into each pipeline step
	op := &v1alpha1.Operation{
		TypeMeta: metav1.TypeMeta{
			APIVersion: v1alpha1.SchemeGroupVersion.String(),
			Kind:       v1alpha1.OperationKind,
		},
		ObjectMeta: wo.Spec.OperationTemplate.ObjectMeta,
		Spec:       *wo.Spec.OperationTemplate.Spec.DeepCopy(),
	}

	for i := range op.Spec.Pipeline {
		step := &op.Spec.Pipeline[i]
		if step.Requirements == nil {
			step.Requirements = &v1alpha1.FunctionRequirements{}
		}
		step.Requirements.RequiredResources = append(step.Requirements.RequiredResources, sel)
	}

	return op, nil
}

```

just a side note you need to load required resources first https://github.com/crossplane/crossplane/blob/main/cmd/crank/alpha/render/op/cmd.go#L172-L179 (needs to be before https://github.com/crossplane/crossplane/blob/main/cmd/crank/alpha/render/op/cmd.go#L146) and allow them as input for LoadOperation https://github.com/crossplane/crossplane/blob/main/cmd/crank/alpha/render/op/load.go#L29C6-L29C19

Comment (bobh66) [reply cmd/crank/alpha/render/op/load.go:55]: Thanks @haarchri !
