### PR TITLE
Apply merge options from patch policy

### LINKED ISSUE #2690: MergeOption: appendSlice is overwriting instead of appending
### What happened?

Hi all, i guess the mergeOption: appendSlice is broken.
Seems like the appendSlice is not respected and the tagset is overwritten.
Is this a known issue?
Thanks

### How can we reproduce it?
I have the following composition with patches

```yaml
  resources:
    - base: 
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: METADATA_UID
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-provider-config
          forProvider:
            acl: private
            locationConstraint: REGION
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            tagging:
              tagSet: 
                - key: namespace
                  value: MY_NAMESPACE
          writeConnectionSecretToRef:
            name: METADATA_NAME-MR-s3bucket-managed-resource
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tagging.tagSet
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
```

My claim has the following:
```yaml
    tags:
      - key: another-tag
        value: with-value
```

So the following would be expected result:
```yaml
            tagging:
              tagSet: 
                - key: namespace
                  value: MY_NAMESPACE
                - key: another-tag
                  value: with-value
```

But i get the following:
```yaml
    tagging:
      tagSet:
      - key: another-tag
        value: with-value
```

### What environment did it happen in?
Crossplane version: 

Crossplane version: 1.4.1

Cloud provider or hardware configuration - aws-provider v0.20.0-rc
Kubernetes version (use kubectl version) - v1.21.2-eks-0389ca3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - EKS
OS (e.g. from /etc/os-release) - Amazon Linux

### PR DESCRIPTION
**Pull request by EdgeJ**
### Description of your changes

Prior to this commit, merge options were not applied to the
paved.MergeValue method and were effectively thrown away. This commit
passes in any options from Policy.MergeOptions, passing in nil if none
were supplied so that fields can be correctly preserved and merged.

Fixes #2690

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Unit test added for preserving map values and arraySlice merges tested with locally running Crossplane and applying XRs to create MRs with appended fields.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: apis/apiextensions/v1/composition_patches.go [hunk 1]
```diff
@@ -276,7 +284,7 @@ func (c *Patch) applyCombineFromVariablesPatch(from, to runtime.Object) error {
 		return err
 	}
 
-	return patchFieldValueToObject(*c.ToFieldPath, out, to)
+	return patchFieldValueToObject(*c.ToFieldPath, out, to, nil)
```
Comment (negz) [inline apis/apiextensions/v1/composition_patches.go:287]: I imagine we might want to pass merge options here too at some point; in fact it's a little misleading that `mergeOptions` are currently ignored by patches of `type: CombineFromComposite` and `type: CombineToComposite`. I don't think it makes sense to implement now though, given that AFAICT it's not actually possible for the combine patch types to produce a map or array.

File: apis/apiextensions/v1/composition_patches.go [hunk 2]
```diff
@@ -166,13 +166,13 @@ func (c *Patch) applyTransforms(input interface{}) (interface{}, error) {
 // patchFieldValueToObject, given a path, value and "to" object, will
 // apply the value to the "to" object at the given path, returning
 // any errors as they occur.
-func patchFieldValueToObject(fieldPath string, value interface{}, to runtime.Object) error {
+func patchFieldValueToObject(fieldPath string, value interface{}, to runtime.Object, mergeOpts *xpv1.MergeOptions) error {
```
Comment (negz) [inline apis/apiextensions/v1/composition_patches.go:169]: I'd prefer `mo` here. It's what the argument to `MergeValue` is named, and I think the type gives enough context for what they are per https://github.com/crossplane/crossplane/blob/b67e7e0/CONTRIBUTING.md#use-descriptive-variable-names-sparingly


```suggestion
func patchFieldValueToObject(fieldPath string, value interface{}, to runtime.Object, mo *xpv1.MergeOptions) error {
```

File: apis/apiextensions/v1/composition_patches.go [hunk 3]
```diff
@@ -166,13 +166,13 @@ func (c *Patch) applyTransforms(input interface{}) (interface{}, error) {
...
 	paved, err := fieldpath.PaveObject(to)
 	if err != nil {
 		return err
 	}
 
-	if err := paved.MergeValue(fieldPath, value, nil); err != nil {
+	if err := paved.MergeValue(fieldPath, value, mergeOpts); err != nil {
```
Comment (negz) [inline apis/apiextensions/v1/composition_patches.go:175]:
```suggestion
	if err := paved.MergeValue(fieldPath, value, mo); err != nil {
```

File: apis/apiextensions/v1/composition_patches.go [hunk 4]
```diff
@@ -205,13 +205,21 @@ func (c *Patch) applyFromFieldPathPatch(from, to runtime.Object) error {
...
+	}
+
 	// Apply transform pipeline
 	out, err := c.applyTransforms(in)
 	if err != nil {
 		return err
 	}
 
-	return patchFieldValueToObject(*c.ToFieldPath, out, to)
+	return patchFieldValueToObject(*c.ToFieldPath, out, to, mergeOpts)
```
Comment (negz) [inline apis/apiextensions/v1/composition_patches.go:222]:
```suggestion
	return patchFieldValueToObject(*c.ToFieldPath, out, to, mo)
```

File: apis/apiextensions/v1/composition_patches.go [hunk 5]
```diff
@@ -205,13 +205,21 @@ func (c *Patch) applyFromFieldPathPatch(from, to runtime.Object) error {
 		return err
 	}
 
+	var mergeOpts *xpv1.MergeOptions
+
+	if c.Policy == nil {
+		mergeOpts = nil
+	} else {
+		mergeOpts = c.Policy.MergeOptions
+	}
```
Comment (negz) [inline apis/apiextensions/v1/composition_patches.go:214]:
```suggestion
	var mo *xpv1.MergeOptions
	if c.Policy != nil {
		mo = c.Policy.MergeOptions
	}
```

Nit: I believe this is a slightly more succinct version of the same thing.

**Review by negz — COMMENTED** [review]
Thanks for catching this @EdgeJ! I wonder if this was a regression or just never worked. 🤔

File: apis/apiextensions/v1/composition_patches.go (hunk 1 above)
Comment (EdgeJ) [reply apis/apiextensions/v1/composition_patches.go:287]: Agreed that passing them in here will make sense once the combine types support arrays/maps.  As you pointed out, I didn't implement it with this PR because of the fact that it's basically a no-op at this point.

**Review by negz — APPROVED** [review]
Thanks for fixing this @EdgeJ!

**Review by hasheddan — COMMENTED** [review]
@negz should this also be backported to `release-1.5` and `release-1.4`?
