### PR TITLE
Fix: enforcedCompositonRef composite sync 

### LINKED ISSUE #6230: `enforcedCompositionRef` conflicting with Claim/Composite sync
### What happened?

We are starting using the `enforcedCompositionRef` feature to migrate from a multiple-composition-per-API to a one-compoistion-per-API setup.

While testing we found to 2 major problems with the behaviour of that parameter:

1. after updating an XRD with added  `enforcedCompositionRef`, this only takes effect after a Crossplane Pod restart
2. the Claim/Composite sync (CSA, not tested with SSA alpha feature) is conflicting with `enforcedCompositionRef`  for the setting of `compositionRef`.
   * this results in Claims/Composites with this:
      ```
      spec:
        claimRef:
          apiVersion: cluster/v1alpha1
          kind: NodePool
          name: tenant-nodepool
          namespace: tenant
        compositionRef:
          name: node-pool-iat
        compositionRevisionRef:
          name: node-pool-34014e3
        compositionSelector:
          matchLabels:
            stage: iat
        compositionUpdatePolicy: Automatic
      ``` 
   * in the events of the XR we see the CompositionSelection-loop (increasing loop interval) :
      ```
      Events:
        Type    Reason                Age                From                                                             Message
        ----    ------                ----               ----                                                             -------
        Normal  CompositionSelection  17m (x2 over 53m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Enforced composition has been selected
        Normal  ComposeResources      9m18s              defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully composed resources
      ```
   * sometimes (e.g. in k9s) you can catch the flicker where shortly `compositionRef` has the desired Composition name
   * however the `compositionRevisionRef` seems to never change.
   * also it is possible to delete the old Composition (here "node-pool-iat"), because none of its CompositionRevision is in use
   * Note: in cases/APIs where there is only a Composite (no Claim, e.g. composed via other Composition), we do not see this behaviour 

### How can we reproduce it?

1. base setup: 
   * XRD (without `enforcedCompositionRef`)
   * 2 Compositions (A + B) for that API
   * 1 deployed test Claim that references composition A (directly `compositionRef` or via `compositionSelector`)
2. update the XRD with an enforcedCompositionRef for composition B
3. trigger manually (or wait) for Crossplane Pod restart
4. look at XRC/XR spec and XR Events (as seen in the examples above)

### What environment did it happen in?
Crossplane version: 1.17.1

### PR DESCRIPTION
**Pull request by ezgidemirel**
### Description of your changes

This PR is a backport to 1.20 of https://github.com/crossplane/crossplane/pull/6683, plus additional functionality to match that of https://github.com/crossplane/crossplane/pull/6881

The `EnforcedCompositionSelector` was caching the CompositeResourceDefinition (XRD) object at initialization time, which meant that changes to the `enforcedCompositionRef` field wouldn't be picked up without restarting the Crossplane pod. This change fixes this behavior by fetching the XRD dynamically on each reconcile.

In addition to that, the PR fixes the claim to composite sync issue when we use composition pipelines. 

I manually tested the PR with the following steps:

- Deployed crossplane v1.20.1 
- Applied the following XRD, compositions and claim
```bash
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.example.org
spec:
  group: example.org
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: MyBucket
    plural: mybuckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                  description: "Bucket name"
              required:
                - bucketName
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.aws.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
  - step: render-resources
    functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          apiVersion: s3.aws.upbound.io/v1beta2
          kind: Bucket
          metadata:
            name: {{ .observed.composite.resource.spec.bucketName }}
            labels:
              testing.upbound.io/example-name: s3
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: "test-user-ezgi"
          spec:
            forProvider:
              region: us-west-1
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.gcp.example.org
  labels:
    provider: gcp
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
  - step: render-resources
    functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          apiVersion: storage.gcp.upbound.io/v1beta1
          kind: Bucket
          metadata:
            name: ezgi
            labels:
              example: "true"
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: "test-user-ezgi"
          spec:
            forProvider:
              location: US
            deletionPolicy: Delete
---
apiVersion: example.org/v1alpha1
kind: MyBucket
metadata:
  name: ezgi-bucket
spec:
  bucketName: "ezgi-test-bucket"
---
apiVersion: v1
items:
- apiVersion: pkg.crossplane.io/v1
  kind: Provider
  metadata:
    name: upbound-provider-aws-s3
  spec:
    ignoreCrossplaneConstraints: true
    package: xpkg.upbound.io/upbound/provider-aws-s3:v1.23.1
- apiVersion: pkg.crossplane.io/v1
  kind: Provider
  metadata:
    name: upbound-provider-family-aws
  spec:
    ignoreCrossplaneConstraints: true
    package: xpkg.upbound.io/upbound/provider-family-aws:v2.1.1
- apiVersion: pkg.crossplane.io/v1
  kind: Provider
  metadata:
    name: upbound-provider-family-gcp
  spec:
    ignoreCrossplaneConstraints: true
    package: xpkg.upbound.io/upbound/provider-family-gcp:v2.1.0
- apiVersion: pkg.crossplane.io/v1
  kind: Provider
  metadata:
    name: upbound-provider-gcp-storage
  spec:
    ignoreCrossplaneConstraints: true
    package: xpkg.upbound.io/upbound/provider-gcp-storage:v1
kind: List
metadata:
  resourceVersion: ""
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: crossplane-contrib-function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.11.0

```
- Patched the XRD to add `enforcedCompositionRef` field
- Restarted crossplane pod
- Verified that the claim and composite refers to different composition revisions
- Deleted resources and upgraded crossplane to the branch version
- Followed the same steps
- Verified that claim and composite refers to the enforced composition

Fixes #6230 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 1]
```diff
@@ -538,13 +537,16 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 	k := xr.GetKind()
 	n := xr.GetName()
 	u := xr.GetUID()
+	r := xr.GetCompositionReference()
```
Comment (jbw976) [inline internal/controller/apiextensions/composite/composition_functions.go]: this file is the only difference from https://github.com/crossplane/crossplane/pull/6683 I believe - do we need to make these changes also in main and release-2.0?

Comment (jbw976) [reply internal/controller/apiextensions/composite/composition_functions.go]: also, i'm not sure i fully understand this change yet. We're saving the basic k8s api metadata here so we can set it on the desired XR before sending it to the API server.

in terms of Crossplane machinery fields, it feels odd that we would need to also save just the composition reference too. If we needed to save crossplane fields in addition to basic k8s api metadata, I would think we'd need to do that for ALL the crossplane fields, not just composition reference. 

What do you think? 🤔

Comment (ezgidemirel) [reply internal/controller/apiextensions/composite/composition_functions.go]: Hey @jbw976, you're right. I was biased about the function pipeline but it turned out that, the values were overwritten by the claim syncer. I updated the last commit and opened a [PR](https://github.com/crossplane/crossplane/pull/6881) to main branch as well.

**Comment by ezgidemirel** [comment]
> Thanks @ezgidemirel! It took me a minute to realize this was a backport PR to v1.20 - I have updated the description to make that more clear for oblivious folks like me 🤪
> 
> So with this PR, we'll have fixes in 1.20, 2.0, and main/2.1, which are the supported releases when 2.1 goes out next week. Makes sense to me.
> 
> > In addition to that, the PR fixes the claim to composite sync issue when we use composition pipelines.
> 
> Can you expand a bit more on what this issue was?
> 
> Do you think that the behavior described by @wotolom in [#6230 (comment)](https://github.com/crossplane/crossplane/issues/6230#issuecomment-3245186816) is entirely because the original fix in #6683 wasn't backported to v1.19? If not, is there anything else we need to do here to completely fix the behavior they are seeing?

The behaviour was exactly what was mentioned in that issue. My claim and composite resources' `compositionRevisionRef` fields were pointing to the correct revision, however the `compositionRef` fields were overwritten afterwards.
