### PR TITLE
fix: improve errors for malformed xpkg examples

### LINKED ISSUE #4776: `crossplane xpkg build` with malformed examples fails with ineffective error message
Hey! First of all thanks for the efforts put into developer experience, its great to see those developments, highly appreciated.

### What happened?

I yesterday played around with the current `xpkg build` from master it in a provider which is currently distributed in the classic 2-images way. What I noticed is that the error messages of the yaml parser (in the case where an example is malformed) are not particularly helpful [1]. In case it fails to parse a document you don't get any hint which of the files / docs are the problem. I haven't found an issue in `up`.  

I would like to see a hint in which file the erroneous document is to find.

[1]: 
```
crossplane: error: xpkg.buildCmd.Run(): failed to build package: failed to parse examples: error converting YAML to JSON: yaml: line 1: did not find expected node content
```

### How can we reproduce it?
Run `crossplane xpkg build` with a malformed yaml, e.g. add a document like this somewhere into the examples.

```yaml
---
# foo bar
# bar baz
---
```

### What environment did it happen in?
Crossplane version: 
master@a6c639ed33a7ca7f57eed0d8d227cf32cc605479.

### PR DESCRIPTION
**Pull request by majiayu000**
### Description of your changes

Improve error context when parsing malformed xpkg examples and add parser tests.

Fixes #4776

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [ ] ~~Run `earthly +reviewable` to ensure this PR is ready for review.~~
- [x] Added or updated unit tests.
- [ ] ~~Added or updated e2e tests.~~
- [ ] ~~Linked a PR or a [docs tracking issue] to [document this change].~~
- [ ] ~~Added `backport release-x.y` labels to auto-backport this PR.~~
- [ ] ~~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

**Comment by phisco** [comment]
@majiayu000 mind checking the [DCO](https://github.com/crossplane/crossplane/pull/6990/checks?check_run_id=59136972801) issue in CI?

**Comment by majiayu000** [comment]
@phisco Thanks for your reminder. Has fixed dco

File: internal/xpkg/parser/examples/parser_test.go [hunk 1]
```diff
@@ -0,0 +1,152 @@
+/*
+Copyright 2023 The Crossplane Authors.
```
Comment (phisco) [inline internal/xpkg/parser/examples/parser_test.go]:
```suggestion
Copyright 2026 The Crossplane Authors.
```

**Comment by majiayu000** [comment]
@phisco  Thanks for your review!
