### PR TITLE
Fix "Missing node in tree error" after updating a package source

### LINKED ISSUE #3985: Missing node in tree error after updating a package source
### What happened?

After updating the source of a package without changing its version, provider/providerrevision fails with `cannot resolve package dependencies: missing node in tree`. 

No problem occurs if the version is changed while changing the source.

### How can we reproduce it?

1. Deploy a provider from one source:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: crossplanecontrib/provider-helm:v0.14.0
```

2. Wait until it is installed/healthy

```
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                   AGE
provider-helm   True        True      crossplanecontrib/provider-helm:v0.14.0   7s
```

3. Update `spec.package` to `xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0`

4. Check provider/providerrevision

```bash
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                                    AGE
provider-helm   True        Unknown   xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0   2m11s

❯ kubectl get providerrevision.pkg
NAME                         HEALTHY   REVISION   IMAGE                                                      STATE    DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-ce18dd03e6e4   Unknown   1          xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0   Active                               2m13s
```

```bash
  Warning  ResolveDependencies  7s (x6 over 36s)       packages/providerrevision.pkg.crossplane.io  cannot resolve package dependencies: missing node in tree
```

### What environment did it happen in?
Crossplane version: 1.11.3

### PR DESCRIPTION
**Pull request by jdillet**
### Description of your changes
This PR fixes "Missing node in tree error" after updating a package source when image is not updated.
The issue happens because package in lock is updated with new source, but providerrevision is not updated because image SHA is not changed (providerrevision name is created from provider name + image SHA).
This causes "Missing node in tree error" when installing the package because of the mismatch between old source and new source for the same provider (or function).

The PR:
- deletes a package from the lock when there is a source mismatch. This allows the reconciler to install the package from updated source.
- adds a unit test.

Fixes #3985 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [x] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet

### CODE REVIEW

File: internal/controller/pkg/revision/dependency.go [hunk 1]
```diff
@@ -137,6 +137,24 @@ func (m *PackageDependencyManager) Resolve(ctx context.Context, pkg runtime.Obje
 		Dependencies: sources,
 	}
 
+	// Delete packages in lock with same name and distinct source
+	// This is a corner case when source is updated but image SHA is not (i.e. relocate same image
+	// to another registry)
+	for _, lp := range lock.Packages {
+		if self.Name == lp.Name &&
+			self.Type == lp.Type &&
+			self.Source != lp.Identifier() {
```
Comment (negz) [inline internal/controller/pkg/revision/dependency.go:146]: Nit: I wouldn't worry about wrapping this. Doesn't seem like the unwrapped line would be very long compared to the rest of the file.

File: internal/controller/pkg/revision/dependency.go [hunk 2]
```diff
@@ -137,6 +137,24 @@ func (m *PackageDependencyManager) Resolve(ctx context.Context, pkg runtime.Obje
...
+			if err := m.RemoveSelf(ctx, pr); err != nil {
+				return found, installed, invalid, err
+			}
+			// refresh the lock to be in sync with the contents
+			if err = m.client.Get(ctx, types.NamespacedName{Name: lockName}, lock); err != nil {
+				return found, installed, invalid, err
+			}
```
Comment (negz) [inline internal/controller/pkg/revision/dependency.go:153]: I wonder whether it'd make sense for `RemoveSelf` to take a pointer to the lock as an argument. That way we wouldn't need to fetch it here afterward.

**Review by negz — COMMENTED** [review]
Nice, thank you for tackling this longstanding issue!

File: internal/controller/pkg/revision/dependency.go (hunk 1 above)
Comment (jdillet) [reply internal/controller/pkg/revision/dependency.go]: Done

File: internal/controller/pkg/revision/dependency.go (hunk 2 above)
Comment (jdillet) [reply internal/controller/pkg/revision/dependency.go:151]: RemoveSelf is doing lock get + update, so it is true that this is adding an extra get that could be avoided by returning the lock from RemoveSelf (I believe with current implementation it would make more sense to return the lock rather that taking it as argument).

At the same time, this block of code won't be generally executed, as it only handles corner-case of relocate same image to different registry. Because of this, I decided to keep the changes at minimum, and not change the method signature, but I'd agree with either keeping it as it is or returning the lock in the method, whichever option you prefer.

Comment (negz) [reply internal/controller/pkg/revision/dependency.go:151]: Let's leave it as is. The extra get here is a bit unfortunate but I agree it's not worth the churn of updating the signature at this point.

**Review by negz — APPROVED** [review]

**Comment by negz** [comment]
@turkenh - Could you sanity check this before we merge? I know you looked into this problem in the past.

**Review by turkenh — APPROVED** [review]
Looking good, thanks for tackling this @jdillet 🙌
