### PR TITLE
fix(render): propagate root composite identity through nested XR trees

### LINKED ISSUE #6956: Render doesn't preserve composite labels
### What happened?

  `crossplane render` produces incorrect `crossplane.io/composite` labels on composed resources when rendering
  nested XRs (XRs that are themselves composed resources of a parent XR).

  **Expected behavior:** When rendering a nested XR that has inherited the `crossplane.io/composite` label from
  its parent, composed resources should receive the same inherited label value (pointing to the root composite).

  **Actual behavior:** `crossplane render` always uses `xr.GetName()` for the `crossplane.io/composite` label,
  ignoring any existing label on the XR. This means composed resources of nested XRs get incorrect labels pointing
   to the nested XR's name instead of the root composite's name.

  For example, with this tree structure:
  Root XR: parent-xr
    └── Nested XR: parent-xr-child (has label crossplane.io/composite: parent-xr)
          └── ManagedResource

  The ManagedResource should have `crossplane.io/composite: parent-xr`, but `crossplane render` produces
  `crossplane.io/composite: parent-xr-child`.

  The same issue affects claim labels (`crossplane.io/claim-name`, `crossplane.io/claim-namespace`) - nested XRs
  inherit these labels from their parent but don't have a `claimReference`, so render fails to propagate them.

  ### How can we reproduce it?

  1. Create a nested XR with inherited labels:
  ```yaml
  apiVersion: example.org/v1
  kind: ChildXR
  metadata:
    name: parent-xr-child
    labels:
      crossplane.io/composite: parent-xr
      crossplane.io/claim-name: my-claim
      crossplane.io/claim-namespace: default
  spec:
    # ...
```

  2. Run crossplane render with this XR and a composition that creates composed resources
  3. Observe that composed resources have:
    - crossplane.io/composite: parent-xr-child (wrong - should be parent-xr)
    - No claim labels (wrong - should inherit from XR's labels)

  Root Cause

  In cmd/crank/render/render.go, SetComposedResourceMetadata uses xr.GetName() directly instead of checking for an
   existing crossplane.io/composite label:

    // Current (incorrect):
    meta.AddLabels(cd, map[string]string{AnnotationKeyCompositeName: xr.GetName()})

    // Should mirror composition_render.go behavior:
    // Use xr.GetLabels()[AnnotationKeyCompositeName] if present, fall back to xr.GetName()

  The actual Crossplane controller in internal/controller/apiextensions/composite/composition_render.go correctly
  propagates labels from the XR, not from xr.GetName().

  What environment did it happen in?

  Crossplane version: main (also affects all versions with crossplane render)

  This is a bug in the offline crossplane render tool, not in the runtime controller.

### PR DESCRIPTION
**Pull request by jcogilvie**
### Description of your changes

  This updates SetComposedResourceMetadata to properly handle nested XRs by
  propagating the root composite's identity through the resource tree. Previously,
  render always used xr.GetName() for the crossplane.io/composite label, which
  produced incorrect labels for composed resources of nested XRs.

  The fix checks xr.GetLabels()[AnnotationKeyCompositeName] before falling back
  to xr.GetName(), mirroring the behavior of RenderComposedResourceMetadata in
  internal/controller/apiextensions/composite/composition_render.go.

  This enables tools like crossplane-diff to accurately render nested XR trees
  by iteratively processing each level with correct identity propagation.

Fixes #6956

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
~~- [ ] Added or updated e2e tests.~~
~~- [ ] Linked a PR or a [docs tracking issue] to [document this change].~~
~~- [ ] Added `backport release-x.y` labels to auto-backport this PR.~~
~~- [ ] Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: cmd/crank/render/render.go [hunk 1]
```diff
@@ -438,17 +438,27 @@ func Render(ctx context.Context, log logging.Logger, in Inputs) (Outputs, error)
 }
 
 // SetComposedResourceMetadata sets standard, required composed resource
-// metadata. It's a simplified version of the same function used by Crossplane.
-// Notably it doesn't handle 'nested' XRs - it assumes the supplied XR should be
-// treated as the top-level XR for setting the crossplane.io/composite,
-// crossplane.io/claim-namespace, and crossplane.io/claim-name annotations.
+// metadata. It mirrors the behavior of RenderComposedResourceMetadata in
```
Comment (adamwg) [inline cmd/crank/render/render.go:441]: Any reason why render can't just call `composite.RenderComposedResourceMetadata` rather than mirroring its behavior here? The only big difference I can see at this point is that `RenderComposedResourceMetadata` fails if the XR doesn't already have the `composite` label; unclear to me whether that would be a problem for render.

Comment (jcogilvie) [reply cmd/crank/render/render.go:441]: I don't think that render requires the composite label as it stands, so adding that requirement might surprise the user.  Normally the controller machinery would set up those labels on the user's behalf, right?  You can create an XR without it, and it'll get auto-added, which I think render tries to mimic.  That would be my primary reason for leaving this here, but I'm happy to be overruled.  

Also, with our attempt to parse this CLI apart from the main bolus of code, should we depend on another internal method?

Comment (adamwg) [reply cmd/crank/render/render.go:441]: > I don't think that render requires the composite label as it stands, so adding that requirement might surprise the user. Normally the controller machinery would set up those labels on the user's behalf, right? You can create an XR without it, and it'll get auto-added, which I think render tries to mimic. That would be my primary reason for leaving this here, but I'm happy to be overruled.

My thinking was that render could set the label elsewhere (e.g., when loading the XR) rather than requiring the user to do it. Definitely wouldn't want the user to have to set labels that aren't required when applying an XR to a running Crossplane.

> Also, with our attempt to parse this CLI apart from the main bolus of code, should we depend on another internal method?

I did have this thought as well. I believe if/when we pull the CLI into its own repo, the bulk of render will stay in c/c, since it already depends on the composite controller as well as other non-trivial internal stuff (`xfn`, `xcrd`). In this world, the `crossplane render` CLI command would consume this code the same way `crossplane-diff` and `up` do today, except the import path would be `pkg/render` instead of `cmd/crank/render`.

That said, limiting how much internal stuff we use in render is still a reasonable goal with the future of the CLI still up in the air a bit. @negz and the other maintainers might have stronger opinions on how much we should duplicate vs. couple, and I'd defer to them.

Comment (jcogilvie) [reply cmd/crank/render/render.go:441]: Maybe we should take that discussion to a different forum?  It kind of dovetails with what we're planning for the #sig-cli meeting right?  

I am a little hesitant to let the big-picture question prevent the little-picture fix I'm after here.  But happy to queue up the big-picture fix right after, whatever we decide that looks like.

Comment (adamwg) [reply cmd/crank/render/render.go:441]: Yep, makes sense :+1: I'm happy for this change to be merged as-is and we can figure out the long-term picture on/after Thursday. I'll resolve this thread and we can wait for a maintainer to approve :-).

Edit: Maybe you have to resolve it? I don't see the resolve button :man_shrugging:

**Review by adamwg — APPROVED** [review]
