### PR TITLE
fix: ignore invalid resources when composing

### LINKED ISSUE #5114: Passing values in a composition to a required OpenAPI field causes an endless reconcile loop
### What happened?

Patching a value from one XR to another XR results via a Parent XR in an endless loop if:

1. there is a OpenAPI `required` field on the Target XR that gets a value from the parent XR status
1. the policy `fromFieldPath: Required` is not set on the Parent Composition field that patches the target XR

image

The below animated gif shows the behavior. Notice that even after the VPC is ready and has propagated the ID, the XTarget XR continues to report a missing field and Crossplane continually creates a new XR name.  When I add the policy (as in https://github.com/stevendborrelli/nested-xrd/blob/32a0fdcbc6e12dc980ee9c9a8be470e47c4e9475/apis/xparent/composition.yaml#L36), it will eventually resolve.

### How can we reproduce it?

Install the composite in https://github.com/stevendborrelli/nested-xrd, set up a default AWS providerconfig and provision `examples/xparent.yaml`

### What environment did it happen in?

* Crossplane version: UXP 1.14.5
* Cloud provider or hardware configuration: Crossplane/Upbound provider-aws v0.47.1
* Kubernetes version (use `kubectl version`) 1.27.1
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) Kind

### LINKED ISSUE #5292: 1.14.5 Native patching behavior change - XR desired state dropped if a resource won't get all required schema values
### What happened?

When one of the resources in composition has a patch to a field that in its schema is required, but the patch lacks `fromFieldPath: Required` policy, XR desired state from other resources patches will be dropped which can lead to deadlock and stopping composition progress. 

This behavior changed, in 1.13.x the resource that lacks required field fails but the desired state of other patches to the XR would be saved and the resource would be created on next reconciliation.

### How can we reproduce it?

Apply manifests below, xrd->compositions->claim

On 1.14.5 it will create second XDummy and in summary 2 DeploymentRuntimeConfig only after adding `fromFieldPath: Required` patch for required value .

Example demo xrd, compositions and claim file:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xdummys.example.org
spec:
  defaultCompositionRef:
    name: test-comp-two
  group: example.org
  names:
    kind: XDummy
    plural: xdummys
  claimNames:
    kind: Dummy
    plural: dummys
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              exampleField:
                type: string  
            required:
            - exampleField
```

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test-comp-one
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XDummy
  resources:
    - name: druntime-one
      base:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: DeploymentRuntimeConfig
        metadata:
          annotations:
            crossplane.io/external-name: druntime-one
        spec: {}
      patches:
      # desired state of this patch will be saved as it is patching MR
      - type: FromCompositeFieldPath
        fromFieldPath: spec.exampleField
        toFieldPath: metadata.annotations.stringFromClaim
      # this one will fail to be saved
      - type: ToCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.annotations.exampleVal

    - name: second-xdummy
      base:
        apiVersion: example.org/v1alpha1
        kind: XDummy
        metadata:
          annotations:
            crossplane.io/external-name: dummy-two
        spec: {}
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.annotations.exampleVal
        toFieldPath: spec.exampleField
        # try without this policy first, 1.13.2 succeeds, 1.14.5 deadlocks
        # policy:
        #   fromFieldPath: Required
```

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test-comp-two
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XDummy
  resources:
    - name: druntime-two
      base:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: DeploymentRuntimeConfig
        metadata:
          annotations:
            crossplane.io/external-name: druntime-two
        spec: {}
      patches:
      - type: ToCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.annotations.exampleVal
```

```yaml
apiVersion: example.org/v1alpha1
kind: Dummy
metadata:
  name: test
spec:
  exampleField: "test string"
  compositionRef:
    name: test-comp-one
```

### What environment did it happen in?
Crossplane version: 1.14.5

Could replicate on eks 1.24 as well as 1.27 kind cluster.

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/5292.
Fixes https://github.com/crossplane/crossplane/issues/5114.

This PR fixes  the stated issues by implementing a change in the resource application approach. Even in cases where one of the composed resources is invalid, we will proceed to apply other resources. This adjustment ensures that eventually consistent Compositions work as intended, while still emitting Warnings events and setting the XR's Sync Condition to false to signal the issue to consumers.

`Sync` and `Ready` conditions will adhere to the following logic:
- for both `Resources` and `Pipeline` compositions: if any of the composed resources fails to apply, the XR's `Sync` condition is set to false.
- only for `Resources` compositions, in the above scenario, also the XR's `Ready` condition is set to false.

While at it, we decided to revise the execution order of the XR status update for `Pipeline` Compositions, ensuring it occurs after the application of composed resources. This modification serves two key purposes: firstly, it ensures the process aligns with the execution order in the PTComposer. Secondly, it prevents an invalid XR status from obstructing the application of composed resources, thereby enabling eventually consistent compositions to subsequently yield a valid XR status.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [x] Added or updated e2e tests.
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [x] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: internal/controller/apiextensions/composite/composition_pt.go [hunk 1]
```diff
@@ -273,6 +273,16 @@ func (c *PTComposer) Compose(ctx context.Context, xr *composite.Unstructured, re
 		o := []resource.ApplyOption{resource.MustBeControllableBy(xr.GetUID()), usage.RespectOwnerRefs()}
 		o = append(o, mergeOptions(filterPatches(t.Patches, patchTypesFromXR()...))...)
 		if err := c.client.Apply(ctx, cd, o...); err != nil {
+			if kerrors.IsInvalid(err) {
+				// NOTE(phisco): we used to catch invalid resources as a
+				// side-effect of the dry-run apply we run to generate a name
+				// for them. We no longer do that, so here we'll just ignore
+				// these errors and remove the resource from cds so that it's
+				// not going to be observed later.
+				cds[i] = nil
```
Comment (phisco) [inline internal/controller/apiextensions/composite/composition_pt.go:282]: we also want to emit an event here actually, I was doublechecking whether we did it on 1.13 and we did: https://github.com/crossplane/crossplane/blob/01c5d2b0308e775e2043f9552631037c23ceaed8/internal/controller/apiextensions/composite/composition_pt.go#L212

Comment (bobh66) [reply internal/controller/apiextensions/composite/composition_pt.go:282]: Do we need a similar change in composition_functions.go - https://github.com/crossplane/crossplane/blob/13c2d1f42c61d332b065f3b20c1db6e10c773c37/internal/controller/apiextensions/composite/composition_functions.go#L409 ?

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_pt.go:282]: Yes, I have to test it, but from the code I'd say so, the code was based on the same assumption

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_pt.go:282]: looks like we always returned early in case of errors when dry-running resources with functions 🤔 https://github.com/crossplane/crossplane/pull/4858/files#diff-e62ddfeee06c113f3ce89d4236b1a8295f2c6e0158d3abc07a866dfb36c75e63L326

**Comment by phisco** [comment]
To recap:
- the function composer always errored out when trying to apply invalid resources, preventing successive resources from being applied AFAICT
- the pt composer in 1.13 used to just ignore resources erroring out on the dry-run apply, while from 1.14 on resources were not validated anymore and were causing the reconciliation to exit preventing successive resources to be applied

Given the eventually consistent nature of Kubernetes and Crossplane I think we should just ignore errors in both cases, has to be understood how to prevent spamming events which was the issue https://github.com/crossplane/crossplane/pull/4858 was trying to solve.

**Comment by phisco** [comment]
A little more details before I forget, at least this is what I understood.

In 1.13 we were only dry-running the first [time](https://github.com/crossplane/crossplane/blob/01c5d2b0308e775e2043f9552631037c23ceaed8/internal/controller/apiextensions/composite/composition_pt.go#L562), [marking](https://github.com/crossplane/crossplane/blob/01c5d2b0308e775e2043f9552631037c23ceaed8/internal/controller/apiextensions/composite/composition_pt.go#L217) resources as having an error, and ignoring invalid resources later on in various [places](https://github.com/crossplane/crossplane/blob/01c5d2b0308e775e2043f9552631037c23ceaed8/internal/controller/apiextensions/composite/composition_pt.go#L240), until they could be applied successfully later. On successive updates which would result in an error applying an existing composed resource, we were erroring out and preventing the rest of resources to be applied.

In 1.14 before https://github.com/crossplane/crossplane/pull/4858, we used to behave exactly the same for both functions and pt composer, catching invalid resources early and ignoring them, applying all resources, still only the first iteration though. After https://github.com/crossplane/crossplane/pull/4858 we stopped catching them early, erroring out and preventing successive resources from being applied altogether. Which caused eventually consistent Compositions to deadlock. (Should these be properly be setting patch policy to required? Probably yes, but it's a breaking change w.r.t  1.13 and it makes sense to be more permissive)

This pull request aims to bubble up such errors at any time, while continuing to apply successive resources, whether it's on the first or n-th reconciliation.

**Comment by phisco** [comment]
Here an example:
<details><summary>XRD and compositions</summary>
<p>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xparents.example.org
spec:
  defaultCompositionRef:
    name: parent
  group: example.org
  names:
    kind: XParent
    plural: xparents
  claimNames:
    kind: Parent
    plural: parents
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              someField:
                # no limits on its value
                type: integer
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xchildren.example.org
spec:
  defaultCompositionRef:
    name: child
  group: example.org
  names:
    kind: XChild
    plural: xchildren
  claimNames:
    kind: Child
    plural: children
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              someField:
                minimum: 2
                type: integer
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: parent
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XParent
  resources:
    - name: child
      base:
        apiVersion: example.org/v1alpha1
        kind: XChild
        spec: {}
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.someField
        toFieldPath: spec.someField
    - name: druntime
      base:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: DeploymentRuntimeConfig
        spec: {}
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.annotations[something]
      - type: ToCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.annotations[exampleVal]
      readinessChecks:
      - type: None
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: child
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XChild
  resources:
    - name: druntime
      base:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: DeploymentRuntimeConfig
        spec: {}
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.annotations[something]
      readinessChecks:
      - type: None
```

</p>
</details> 

Applying the following XR succeeds:
<details><summary>test XR</summary>
<p>

```yaml
---
apiVersion: example.org/v1alpha1
kind: Parent
metadata:
  name: test
spec:
  someField: 2
```

image

</p>
</details>

Updating it to have `spec.someField: 1` errors out:
<details><summary>screenshot</summary>
<p>

image


</p>
</details> 

While creating it from the beginning with `spec.someField: 1`, but at least proceeds to deploy the DeploymentConfig and to set the annotation on the composite resource:
<details><summary>screenshot</summary>
<p>

image

</p>
</details>

**Comment by phisco** [comment]
If I got it correctly this would address https://github.com/crossplane/crossplane/issues/5114 too

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 2]
```diff
@@ -495,10 +495,18 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 		// this prevents multiple XRs composing the same resource to be
 		// continuously alternated as controllers.
 		if err := c.client.Patch(ctx, cd.Resource, client.Apply, client.ForceOwnership, client.FieldOwner(ComposedFieldOwnerName(xr))); err != nil {
+			if kerrors.IsInvalid(err) {
+				// We don't want to return an error here, because we want to
+				// continue to apply other composed resources. We'll just return
+				// an event and mark the resource as not ready
+				events = append(events, event.Warning(reasonCompose, errors.Wrapf(err, errFmtApplyCD, name)))
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:502]: Currently when using functions `events` is only used to accumulate "results" that are returned by functions. This information is useful but I'm not sure how I feel about mixing in events produced by the `Compose` code as well.

File: internal/controller/apiextensions/composite/reconciler.go [hunk 3]
```diff
@@ -659,6 +661,13 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
 			id = strconv.Itoa(i)
 		}
 
+		if !cd.Synced {
+			log.Debug("Composed resource is not yet synced", "id", id)
+			unsynced = append(unsynced, cd)
+			r.record.Event(xr, event.Normal(reasonCompose, fmt.Sprintf("Composed resource %q is not yet synced", id)))
```
[the remark this answers is not in the document]
Comment (negz) [reply internal/controller/apiextensions/composite/reconciler.go:667]: I wonder if we could just set `Ready = false` when we can't apply a composed resource, rather than introducing a new Synced field? I'm not convinced there's a significant value in making the distinction.

The reason we're not just returning early when we hit an invalid composed resource is because we think the composed resource might eventually become valid. If that is the case, I think it's fair to think of it as "not ready yet".

On the other hand it's possible the composed resource could just stay invalid forever until a human intervenes. If that is the case, maybe "ready" would be misleading.

[the remark this answers is not in the document]
Comment (phisco) [reply internal/controller/apiextensions/composite/reconciler.go:667]: Right now we set it to synced false in case of errors, and so we did before 1.14. It makes sense to me to have it still be marked as ready but possibly not synced, it means it's still healthy, just not updated to the latest desired state for some reason.

**Comment by bobh66** [comment]
I tested this PR and verified that it fixes the problem we were seeing on 1.14

**Comment by phisco** [comment]
I now noticed we also marked as not ready a resource [here](https://github.com/crossplane/crossplane/pull/5365/files#diff-574bed872a28203735722ddf7a98e52ad596702e555ed0dda6525e4e578481f2L301), which per the original 1.14 implementation was a code path we got into when the resource didn't dry-run successfully on the first creation.

But this made me think I might have misinterpreted the `Ready` and `Synced` conditions for an `XR`. @negz, could you provide your definitions?

File: internal/controller/apiextensions/composite/composition_pt.go [hunk 4]
```diff
@@ -273,6 +273,21 @@ func (c *PTComposer) Compose(ctx context.Context, xr *composite.Unstructured, re
...
+				// this means the resource will never be valid or it will if we
+				// run again the composition after some other resource is
+				// created or updated successfully. So, we emit a warning event
+				// and move on.
+				events = append(events, event.Warning(reasonCompose, errors.Wrap(err, errApplyComposed)))
+				// We unset the cd here so that we don't try to observe it
+				// later. This will also mean we report it as not ready and not
+				// synced. Resulting in the XR being reported as not ready nor
+				// synced too.
+				cds[i] = nil
```
Comment (phisco) [inline internal/controller/apiextensions/composite/composition_pt.go:287]: I actually realised this is probably not what we want. Originally setting an element of cds to nil meant the resource hadn't been created at all (because we couldn't dry-run it), so it made sense to skip observing it below, setting it to ready false as it didn't exist. But now it could mean we couldn't just update it, so we should still report it's readiness correctly if possible. But I'm struggling to find the right way to do it keeping the change as small as possible. Any thought @negz?

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_pt.go:287]: One thing not clear to me is where in here we get the observed resources to feed into the patches, is the assumption that the Apply will also update the status instead of observing composed resources and feeding them to the composition logic as the function composer does? I can see only a [Get](https://github.com/crossplane/crossplane/blob/850a0d494c53393e9b94744597fe14e50081b599/internal/controller/apiextensions/composite/composition_pt.go#L481), but resources are not persisted anywhere, am I missing something?

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_pt.go:287]: if we don't get observed resources it looks like that would be a regression w.r.t. 1.12 as [here](https://github.com/crossplane/crossplane/blob/13c2d1f42c61d332b065f3b20c1db6e10c773c37/internal/controller/apiextensions/composite/composition_pt.go#L220-L223) we would run patches to the environment without the resources status, while we did properly handle it in 1.12 [here](https://github.com/crossplane/crossplane/blob/5b491478367e20202ad85cb57ad2e94eebb0320a/internal/controller/apiextensions/composite/composition_ptf.go#L548).

File: internal/controller/apiextensions/composite/reconciler.go [hunk 5]
```diff
@@ -667,7 +676,19 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+	var result *reconcile.Result
+	if len(unsynced) > 0 {
+		// We want to requeue to wait for our composed resources to
+		// become ready, since we can't watch them.
+		names := make([]string, len(unsynced))
+		for i, cd := range unsynced {
+			names[i] = string(cd.ResourceName)
+		}
+		xr.SetConditions(xpv1.ReconcileError(errors.New(errSyncResources)).WithMessage(fmt.Sprintf("Unsynced resources: %s", resource.StableNAndSomeMore(resource.DefaultFirstN, names))))
+		result = &reconcile.Result{Requeue: true}
```
Comment (phisco) [inline internal/controller/apiextensions/composite/reconciler.go:688]: We could requeue after the poll interval here too to improve on #5007

**Comment by phisco** [comment]
I thought this could help with #5007, but that's about the XR's status, which would still result in an error and therefore in the resource being requeued.

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 2 above)
Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:483]: True, but I don't see any issue extending its usage to events caused by other non-terminal issues.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 6]
```diff
@@ -475,32 +515,12 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 	// NOTE(phisco): Here we are fine using a hardcoded field owner as there is
 	// no risk of conflict between different XRs.
 	if err := c.client.Status().Patch(ctx, xr, client.Apply, client.ForceOwnership, client.FieldOwner(FieldOwnerXR)); err != nil {
+		// Note(phisco): here we are fine with this error being terminal, as
+		// there is no other resource to apply that might eventually resolve
+		// this issue.
```
Comment (phisco) [inline internal/controller/apiextensions/composite/composition_functions.go:520]: It's not extremely clear from the diff, so let me make it explicit, I moved applying the XR status at the bottom to mirror the pt composer's behaviour, also because it could again be a source of issues with eventually consistent compositions to prevent composed resources to be applied due to an invalid composite status, which might become valid once composed resources are applied.

**Comment by negz** [comment]
> But this made me think I might have misinterpreted the Ready and Synced conditions for an XR. @negz, could you provide your definitions?

* `Ready` means that the thing the XR conceptually represents is ready to use.
* `Synced` means that the XR controller successfully "synced" (i.e. reconciled) its desired state.

There's an asymmetry in the scope of these conditions.

For an XR to be ready, all of its composed resources must be ready. The thing the XR conceptually represents can't really be ready until all the things it's composed of are ready. There could be nuances here, so we give folks fine-grained control over what constitutes 'ready' for composed resources.

For an XR to by synced, it just needs to successfully reconcile desired with actual state. The composed resources being synced (successfully applying _their_ desired state) doesn't affect whether the XR is synced.

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 6 above)
Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:520]: > t could again be a source of issues with eventually consistent compositions to prevent composed resources to be applied due to an invalid composite status

@phisco What's an example of an invalid XR status that might eventually become valid? I'm wondering whether this is a real concern.

Here's two I can think of:

1. A status field is required (per the XRD OpenAPI schema), but is not yet being set.
2. A status field is a particular type (per the XRD OpenAPI schema), but you're trying to set the wrong type.

I think 2 would block forever regardless of when we update the XR status. If you're setting an invalid type, it's presumably not going to become valid when one of the composed resources was updated. Or if it does, that seems like your Composition probably still has a bug, right?

I could imagine 1 resolving itself when a composed resource was created/ready (e.g. because you're deriving the status from a composed resource). However, I think it's nonsensical/an anti-pattern to have a required status field in the first place. If and when we have a guide to writing XRDs (https://github.com/crossplane/docs/issues/564) I'd include this.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:520]: Could be a required field, but also a validation rule, or an integer with a minimum value. I agree it doesn't make much sense to set those in the status, probably, but I don't see any reason not to do it now that I noticed it 😅

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:520]: Invalid composed resources are not blocking now (with this patch). Did you mean other types of errors?

File: internal/controller/apiextensions/composite/reconciler.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (phisco) [reply internal/controller/apiextensions/composite/reconciler.go:667]: `Composed resource is not yet synced` was to mirror `Composed resource is not yet ready`.
But I agree it could be misleading, to avoid being too specific risking breaking this assumption later on, I'd rather continue talking about it being synced or not. The whole point is that we couldn't update/create a composed resource according to the current desired state for the composite. Maybe `Couldn't sync Composed resources`?

File: internal/controller/apiextensions/composite/composition_pt.go (hunk 4 above)
Comment (phisco) [reply internal/controller/apiextensions/composite/composition_pt.go:287]: Makes sense to me, but I think we can start from this smaller change already solving the issues at hand and only later, if we feel it's worth the time, rework it more aggressively to fix https://github.com/crossplane/crossplane/issues/5388 too. If we agree this solution is good enough I can work on adding some e2e tests, so that we'll have some confidence refactoring this in the future.

Comment (negz) [reply internal/controller/apiextensions/composite/composition_pt.go:287]: @phisco I'm all for a smaller change.

Weren't you saying though that there's still another issue in the `PTComposer`? If a composed resource exists, but we can't update it because it's now invalid, we won't be able to check its readiness and will thus report it's unready.

Is that right?

File: internal/controller/apiextensions/composite/reconciler.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (negz) [reply internal/controller/apiextensions/composite/reconciler.go:667]: I think we may be talking past each other - maybe we can sync on this live?

I think we have different understanding of what "synced" means.

File: internal/controller/apiextensions/composite/composition_pt.go (hunk 4 above)
Comment (negz) [reply internal/controller/apiextensions/composite/composition_pt.go:287]: Just chatted to @phisco on Zoom. There is still the other issue pointed out in the preceding comment, but we'll defer addressing that to another PR. Even without fixing that issue this PR still moves us forward to a better state.

File: internal/controller/apiextensions/composite/reconciler.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (negz) [reply internal/controller/apiextensions/composite/reconciler.go:667]: @phisco and I just chatted on Zoom.

We'll change the wording in the error string to say something like applied instead of synced, to avoid confusion with the composed resource's synced status condition.

The `cd.Synced` struct field is less of an issue. I could see a case for it being `Synced` there (after all `Ready` already doesn't _strictly_ mean the composed resource's `Ready` status condition, but instead our general assessment of whether it's ready). I could go either way on that.

File: internal/controller/apiextensions/composite/reconciler.go [hunk 7]
```diff
@@ -706,10 +699,39 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+// updateXRConditions updates the conditions of the supplied composite resource
+// based on the supplied composed resources. It returns true if the XR should be
+// requeued immediately.
+func updateXRConditions(xr *composite.Unstructured, unsynced, unready []ComposedResource) (requeueImmediately bool) {
+	readyCond := xpv1.Available()
+	syncedCond := xpv1.ReconcileSuccess()
+	if len(unsynced) > 0 {
+		// We want to requeue to wait for our composed resources to
+		// become ready, since we can't watch them.
+		syncedCond = xpv1.ReconcileError(errors.New(errSyncResources)).WithMessage(fmt.Sprintf("Unsynced resources: %s", resource.StableNAndSomeMore(resource.DefaultFirstN, getComposerResourcesNames(unsynced))))
```
Comment (negz) [inline internal/controller/apiextensions/composite/reconciler.go:714]: Should this talk about "invalid" resources rather than "unsynced", to match the event recorded above?

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 6 above)
Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:520]: > Did you mean other types of errors?

Yeah, either transient errors (e.g. network connectivity etc) or something that requires human intervention to fix (e.g. RBAC issues)

**Review by negz — APPROVED** [review]
Approving to unblock, but I left a comment for one more place I think we should `s/unsynced/invalid`.

**Comment by phisco** [comment]
e2e failures are also on master, we'll have to investigate them, but we can merge this.
