### PR TITLE
fix: exit on fatal handling extra resources

### LINKED ISSUE #5824: Unhelpful Error message when Composition Function with Extra Resources errors
### What happened?

I am developing a Composition which uses Extra Resources. My template works fine in the first iteration where I request ExtraResources. In the Second Iteration the Template errors due to some issue.
Crossplane does not publish the error from the Composition function but instead only says:
`crossplane: error: cannot render composite resource: requirements didn't stabilize after the maximum number of iterations (5)`

I think the reason Crossplane acts the way it does is due to the CompositionFunction keeps switching between requesting ExtraResources and erroring (and therefore not requesting ExtraResources). 

I think this should be handled more gracefully by crossplane. 

### How can we reproduce it?

https://gist.github.com/Avarei/c08da88a39142ef156264229f72d4d32

composition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bad-error-example
spec:
  compositeTypeRef:
    apiVersion: example/v1
    kind: xFoo
  mode: Pipeline
  pipeline:
    - step: template
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: ExtraResources
            requirements:
              icecream:
                apiVersion: example/v1
                kind: Example
                matchLabels: {}
            ---
            {{- if $.extraResources.icecream }}
            {{- fail "i want to fail" }}
            {{- end }}
```

extra.yaml
```yaml
---
apiVersion: example/v1
kind: Example
metadata:
  name: foo
```

function.yaml
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: ghcr.io/avarei/function-go-templating:extra-resources-2
```

xr.yaml
```yaml
apiVersion: example/v1
kind: xFoo
metadata:
  name: myfoo
```

with all the files present run

```sh
crossplane beta render --extra-resources=extra.yaml xr.yaml composition.yaml function.yaml
```

### What environment did it happen in?
Crossplane version: v1.16.0

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/5824.

In case of fatal results and "flapping" requirements, e.g. a function returning some requirements, getting the resources back, then returning a fatal result and empty requirements, we were always hitting the max number of allowed iterations hiding the actual results from the user. Both in `crossplane beta render` and in the main implementation.

Breaking out of the loop in case of fatal errors and letting the main branch of the code handle it.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 1]
```diff
@@ -346,6 +346,7 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 		// Used to store the response of the function at the previous iteration.
 		var rsp *v1beta1.RunFunctionResponse
 
+	extraResourcesLoop:
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:349]: 😭 I've always thought this named loop feature was some of the ugliest syntax in all of Go.

That's subjective though, so not a blocker. On the other hand the broader pipeline loop feels like it's become very very long. I think it's getting a bit hard to reason about. I might try see if it's possible to restructure today, maybe break some of it out into distinct functions.

**Review by negz — APPROVED** [review]

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 1 above)
Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:349]: Yeah, @negz, mixed feelings here too, it has a vintage look that I kind of like, but I get your point 😂 I just didn't want to refactor it the day before cutting the release, but given that tomorrow I'll start the code freeze I can refactor it before merging.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 2]
```diff
@@ -624,6 +570,61 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 	return CompositionResult{ConnectionDetails: d.GetComposite().GetConnectionDetails(), Composed: resources, Events: events, Conditions: conditions}, nil
 }
 
+func (c *FunctionComposer) runFunction(ctx context.Context, fn v1.PipelineStep, req *v1beta1.RunFunctionRequest) (*v1beta1.RunFunctionResponse, error) {
```
Comment (negz) [inline internal/controller/apiextensions/composite/composition_functions.go:573]: This is definitely an improvement, but I'm not usually a fan of taking a chunk of code and breaking it out into a private method, especially if it's only called in one place.

If I look at how this method uses its `*FunctionComposer`:

* It calls `c.pipeline.RunFunction` - it's also the only thing that calls that method.
* It uses `c.composite.ExtraResourcesFetcher` to fetch extra resources (if enabled)

This makes me wonder whether it could be refactored to become a new implementation of the existing `FunctionRunner` interface that takes an underlying `FunctionRunner` (e.g. the existing `PackagedFunctionRunner`) and wraps it to add extra resources support.

At a glance I think it'd be a pretty small change. You could use the extra resources feature flag to determine whether `Compose` should use a bare `PackagedFunctionRunner`, or one wrapped with extra resources support.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:573]: Get your point, I'll be off for the rest of the week, I'd get this one merged as is and follow up with a refactor adding some tests too.

Comment (negz) [reply internal/controller/apiextensions/composite/composition_functions.go:573]: I ended up deciding to "quickly" tackle it myself today: https://github.com/crossplane/crossplane/pull/5883. (Spoiler alert: it's never as quick as I think it'll be.)

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_functions.go:573]: Thanks! Yeah, it never is. That's why I kind of liked the named loop fix. It was actually quick and concise.
