### PR TITLE
fix: crossplane xpkg init doesn't close file

### LINKED ISSUE #5717: `crossplane xpkg init` doesn't close file
### What happened?

See https://github.com/crossplane/crossplane/pull/5632/files

### What environment did it happen in?
Crossplane version:

### PR DESCRIPTION
**Pull request by cychiang**
### Description of your changes
Based on the previous #5632 with the fix for linting.

I believe it's safe to not handle the error. The whole function is doing read only, and not doing any write operation.

Fixes #5717

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added or updated unit tests.
- [ ] Added or updated e2e tests.
- [x] Linked a PR or a [docs tracking issue] to [document this change].
- [ ] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: cmd/crank/beta/xpkg/init.go [hunk 1]
```diff
@@ -235,6 +235,7 @@ func printFile(w io.Writer, path string) error {
 	if _, err := fmt.Fprintf(w, "\n%s\n", content); err != nil {
 		return errors.Wrap(err, "failed to write to stdout")
 	}
+	defer f.Close() //nolint:errcheck // It's safe to ingore the error here.
```
Comment (bobh66) [inline cmd/crank/beta/xpkg/init.go:238]: This should probably be right after the `os.Open()` so that it will be executed on all of the failure legs.

Comment (cychiang) [reply cmd/crank/beta/xpkg/init.go]: Thanks for the feedback, fix it!

Comment (negz) [reply cmd/crank/beta/xpkg/init.go]: Looks like a typo in `ignore`. Also, would be useful to say why it's safe to ignore. I assume because the file was only open for reading, not writing.

Comment (cychiang) [reply cmd/crank/beta/xpkg/init.go]: Yes, I think the same. The whole function is doing read only and not write so I think no need to handle any special case. 

I update the comment, and description in the PR.

**Review by negz — APPROVED** [review]

**Comment by negz** [comment]
Thank you!

**Review by phisco — APPROVED** [review]
