### PR TITLE
fix: rename `--webhook-enabled` flag

### LINKED ISSUE #6412: Rename `--webhooks-enabled` and `--automatic-dependency-downgrade-enabled` flags
### What happened?

`--webhooks-enabled` has been around for a long time.  #6234 added `--automatic-dependency-downgrade-enabled` recently. It's only used when the alpha `--enable-dependency-version-upgrades` flag is enabled. i.e. It's part of that feature.

All other Crossplane flags that enable something are in the form `--enable-foo`, not `--foo-enabled`. There are many more `--enable-foo` flags than `--foo-enabled` flags. `--foo-enabled` uses the [passive voice](https://www.grammarly.com/blog/sentences/active-vs-passive-voice/), while `--enable-foo` uses the active voice. Most docs linters recommend the active voice as easier for users to understand.

I'd like to rename the flags to:

* `--enable-webhooks`
* `--enable-dependency-version-downgrades`

We need to make sure we don't break existing users of the `--webhooks-enabled` flag, so I suggest we:

* Add a new `--enable-webhooks` flag that does the same thing as `--webhooks-enabled`
* Hide `--webhooks-enabled` in the help text
* If `--webhooks-enabled` is specified, log a warning that it'll be removed in Crossplane vNext (probably v2)

We can just rename `--enable-dependency-version-downgrades` without worrying about breaking people, because it's behind an alpha feature flag.

### PR DESCRIPTION
**Pull request by Sajfer**
### Description of your changes

Renamed `webhooks-enabled` to `enable-webhooks`.
Renamed `autoamtic-dependency-downgrade-enabled` to `enable-automatic-depency-version-downgrades`.

Fixes #6412

I have: 

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `earthly +reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

**Comment by negz** [comment]
Thank you!

I ended up renaming the dependency version downgrade flag in https://github.com/crossplane/crossplane/pull/6422/commits/0013a3fea4c605ae6e92ceb02640230320fb10e5. Would you mind updating this PR to just update the webhook flag? That part looks good to me.

File: cmd/crossplane/core/core.go [hunk 1]
```diff
@@ -103,8 +103,9 @@ type startCommand struct {
 	MaxReconcileRate                 int           `default:"100" help:"The global maximum rate per second at which resources may checked for drift from the desired state."`
 	MaxConcurrentPackageEstablishers int           `default:"10"  help:"The the maximum number of goroutines to use for establishing Providers, Configurations and Functions."`
 
-	WebhookEnabled                      bool `default:"true"  env:"WEBHOOK_ENABLED"                        help:"Enable webhook configuration."`
-	AutomaticDependencyDowngradeEnabled bool `default:"false" env:"AUTOMATIC_DEPENDENCY_DOWNGRADE_ENABLED" help:"Enable automatic dependency version downgrades. This configuration requires the 'EnableDependencyVersionUpgrades' feature flag to be enabled."`
+	WebhookEnabled                    bool `default:"true"  env:"WEBHOOK_ENABLED"                      hidden:""`
+	EnableWebhook                     bool `default:"true"  env:"ENABLE_WEBHOOK"                       help:"Enable webhook configuration."`
```
Comment (negz) [inline cmd/crossplane/core/core.go:107]: Nit: Please name this `EnableWebhooks` and `ENABLE_WEBHOOKS`, since these days we have more than one.

**Comment by Sajfer** [comment]
Removed all changes to dependencyVersionDowngrade.

**Review by negz — APPROVED** [review]

**Comment by negz** [comment]
@Sajfer Looks like this now needs a rebase but once that's done I'll merge.

File: cmd/crossplane/core/core.go [hunk 2]
```diff
@@ -105,7 +105,9 @@ type startCommand struct {
 	MaxReconcileRate                 int           `default:"100" help:"The global maximum rate per second at which resources may checked for drift from the desired state."`
 	MaxConcurrentPackageEstablishers int           `default:"10"  help:"The the maximum number of goroutines to use for establishing Providers, Configurations and Functions."`
 
-	WebhookEnabled bool `default:"true" env:"WEBHOOK_ENABLED" help:"Enable webhook configuration."`
+	WebhookEnabled                      bool `default:"true"  env:"WEBHOOK_ENABLED"                        hidden:""`
+	EnableWebhooks                      bool `default:"true"  env:"ENABLE_WEBHOOKS"                        help:"Enable webhook configuration."`
+	AutomaticDependencyDowngradeEnabled bool `default:"false" env:"AUTOMATIC_DEPENDENCY_DOWNGRADE_ENABLED" help:"Enable automatic dependency version downgrades. This configuration requires the 'EnableDependencyVersionUpgrades' feature flag to be enabled."`
```
Comment (jbw976) [inline cmd/crossplane/core/core.go:110]: i'm not sure the rebase was done correctly, it looks like this `AutomaticDependencyDowngradeEnabled` flag is being re-added after @negz removed it in https://github.com/crossplane/crossplane/commit/0013a3fea4c605ae6e92ceb02640230320fb10e5#diff-20d88315192c28a14e8d19b9042c1dfbfad06ce54916ab4b387dda1aae5e2894L114.

This should not be added back, right?

File: cmd/crossplane/core/core.go [hunk 3]
```diff
@@ -237,6 +239,9 @@ func (c *startCommand) Run(s *runtime.Scheme, log logging.Logger) error { //noli
 	if !c.EnableCompositionFunctionsExtraResources {
 		log.Info("Extra Resources are GA and cannot be disabled. The --enable-composition-functions-extra-resources flag will be removed in a future release.")
 	}
+	if !c.WebhookEnabled {
+		log.Info("The --webhooks-enabled flag is deprecated, it is replaced with --enable-webhooks and will be removed in a future release.")
```
Comment (jbw976) [inline cmd/crossplane/core/core.go:243]: i think the old flag name is `--webhook-enabled` (not plural), so this message should use that

**Review by jbw976 — CHANGES_REQUESTED** [review]
@Sajfer could you take another look at the changes here after the rebase was done? I want to make sure I'm looking at it correctly 😅

File: cmd/crossplane/core/core.go (hunk 3 above)
Comment (Sajfer) [reply cmd/crossplane/core/core.go]: Fixed

**Comment by Sajfer** [comment]
Fixed it now, sorry for all the trouble.

File: cmd/crossplane/core/core.go (hunk 2 above)
Comment (Sajfer) [reply cmd/crossplane/core/core.go]: Removed it again.

**Comment by negz** [comment]
Thanks @Sajfer!
