### PR TITLE
Fix XRD controller restart to detect all spec changes

### LINKED ISSUE #2024: Can't update `connectionDetails` for existing resources
### What happened?

I had a typo in the name of the connection secret. CompositeResourceDefinition had "awsSecretAccessKey" while in the Composition object I had "awsSecretAccesskey" in connectionDetails (or the other way around). After fixing the typo (sorry, I don't remember which one had the wrong name) the generated connection secret didn't have awsSecretAccessKey, only awsAccessKeyID.

I've deleted the existing claim and created a new one, but still the same result.

I've deleted and recreated the Composition/CompositeResourceDefinition which fixed the issue.

I haven't used a Configuration, as I'm installing the Composition/CompositeResourceDefinition using a Helm chart.

### How can we reproduce it?

Composition relevant part:
```
    - base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMAccessKey
        metadata:
          name: METADATA_UID
        spec:
          deletionPolicy: Delete
          forProvider:
            accessKeyStatus: Active
            userNameSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            name: METADATA_UID-iam-access
            namespace: kore-crossplane
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-iam-access-key"
      connectionDetails:
        - name: awsAccessKeyID
          fromConnectionSecretKey: username
        - name: awsSecretAccessKey
          fromConnectionSecretKey: password
```

CompositeResourceDefinition relevant part:
```
  connectionSecretKeys:
    - awsAccessKeyID
    - awsSecretAccessKey
```

Crossplane version: 0.14.0

### LINKED ISSUE #6328: New `connectionSecretKeys` don't Propagate to Secrets
### What happened?

When adding new keys to `connectionSecretKeys` in a CompositeResourceDefinition, secrets won't have the new keys until crossplane is restarted. This includes secrets of Composite Resources created after the keys are added.

### How can we reproduce it?

1. Create a CompositeResourceDefinition with `connectionSecretKeys` populated.
2. Create a Composition that outputs connection details for those keys.
3. You might have to create an instance of the XRD here in order to replicate? Not sure
4. Add a new key to `connectionSecretKeys`.
5. Update the Composition to output to that key.
6. Create a new Composite Resource that references the XRD and Composition.
7. Examine the created secret.
8. The new key is missing.
9. Restart crossplane deployment
10. The new key is now present in the created secret.

### What environment did it happen in?
Crossplane version: v1.19.0

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Fixes #6328
Fixes #2024
Related to #6736

When XRD spec fields change, the XR controller doesn't always restart automatically. Users must manually restart the Crossplane deployment for some changes to take effect.

The existing restart logic only detected referenceable version changes. This missed other spec changes like connection details modifications.

This PR replaces the referenceable version based detection with generation-based controller restart detection using the existing condition system. The ControllerNeedsRestart() helper checks if the WatchingComposite condition's observedGeneration differs from the current metadata.generation. When any XRD spec change increments metadata.generation, the mismatch triggers an automatic controller restart.

The E2E test validates the functional impact by verifying that composition selection changes from test-composition-v1 to test-composition-v2 when the referenceable version changes, proving the controller restart worked correctly.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [x] Added or updated e2e tests.
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: internal/controller/apiextensions/definition/reconciler.go [hunk 1]
```diff
@@ -630,3 +631,23 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+func ControllerNeedsRestart(d *v1.CompositeResourceDefinition) bool {
+	c := d.GetCondition(v1.TypeEstablished)
+
+	// Only check if we have a WatchingComposite condition
+	if c.Reason != v1.ReasonWatchingComposite {
+		return false
+	}
+
+	// If observedGeneration is 0, the condition was never properly set
+	if c.ObservedGeneration == 0 {
```
Comment (jbw976) [inline internal/controller/apiextensions/definition/reconciler.go:647]: remind me how this happens - would this be a condition that was set in the past before scott added observedGeneration support in conditions? or are there other reasons? 🤔

File: test/e2e/apiextensions_xrds_test.go [hunk 2]
```diff
@@ -83,3 +83,57 @@ func TestXRDValidation(t *testing.T) {
...
+				funcs.ApplyResources(FieldManager, manifests, "xr-before-change.yaml"),
+				funcs.ResourcesCreatedWithin(30*time.Second, manifests, "xr-before-change.yaml"),
+				// XR should select v1 composition because referenceable version is v1
+				funcs.ResourcesHaveFieldValueWithin(1*time.Minute, manifests, "xr-before-change.yaml", "spec.crossplane.compositionRef.name", "test-composition-v1"),
+			)).
+			Assess("UpdateXRDToV2Referenceable", funcs.AllOf(
+				funcs.ApplyResources(FieldManager, manifests, "xrd-v2-referenceable.yaml"),
+				funcs.ResourcesCreatedWithin(30*time.Second, manifests, "xrd-v2-referenceable.yaml"),
+				// Wait for controller to restart with new generation
+				funcs.ResourcesHaveConditionWithin(1*time.Minute, manifests, "xrd-v2-referenceable.yaml", apiextensionsv1.WatchingComposite()),
```
Comment (jbw976) [inline test/e2e/apiextensions_xrds_test.go:120]: is there a potential race here on this check? e.g., the XRD already had an Established condition with reason WatchingComposite that we verified on line 108. Is it possible that we are checking it again here and seeing it again before it has cycled through TerminatingComposite and back to WatchingComposite (if that is the correct state transition)? 

in other words, should we also be checking the observed generation of this condition, to make sure it has increased?

**Review by jbw976 — APPROVED** [review]
Nice, this looks like it will be a good check to catch many cases of XRDs being updated and needing an XR controller restart.

Just a couple questions for clarification, otherwise looks good! 🙇‍♂️

File: internal/controller/apiextensions/definition/reconciler.go (hunk 1 above)
Comment (negz) [reply internal/controller/apiextensions/definition/reconciler.go:647]: It probably couldn't happen in reality TBH. `GetCondition` above could return an empty condition struct that'd have `ObservedGeneration == 0`, but I'd also expect it to have `c.Reason == ""` and thus return at the check above.

File: test/e2e/apiextensions_xrds_test.go (hunk 2 above)
Comment (negz) [reply test/e2e/apiextensions_xrds_test.go:120]: We should but we can't until we address https://github.com/crossplane/crossplane/issues/6805. There's a comment block about this above the test.
