### PR TITLE
fix(intializer): update storage version of CompositionRevision CRs in etcd

### LINKED ISSUE #4400: crossplane core fails to start up : "cannot apply crd"
### What happened?
After upgrading from 1.7.0 to 1.12.2  the crossplane core doesn't startup.   We see error messages like 

```
crossplane: error: cannot initialize core: cannot apply crd: 
cannot patch object: CustomResourceDefinition.apiextensions.k8s.io 
"compositionrevisions.apiextensions.crossplane.io" is invalid: 
status.storedVersions[1]: Invalid value: "v1": must appear in spec.versions

```

### How can we reproduce it?
TBD.   We have at least 1 deploy where the problem didn't happen and 1 where it did.
They both went through the same upgrade of Crossplane.   However the one that is showing the problem is actually at least a couple years old and has gone through upgrades of k8s while the other was just created within the last month.

NOTE:  We saw a similar situation with service-catalog CRD in May of last year.    What I am saying is, while the symptoms were very different back then the determining factor for which deployments did or did not show the symptoms was whether k8s itself was an 'old' deploy that had been upgraded or if it was a 'young' deploy which had not been upgraded.

### What environment did it happen in?
Crossplane version:  1.12.2
k8s: 1.25.10 <!-- will try to get history of k8s upgrades 
k8s distro :  aws <!-- Teammate is checking how widespread this problem is, could be on others as well
os: Unavailable at this time
kernel: Unavailable at this time

### PR DESCRIPTION
**Pull request by sttts**
### Description of your changes

Fixes #4400

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] ~Added or updated unit **and** E2E tests for my change.~
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
related to #4400

**Review by phisco — APPROVED** [review]

**Review by ezgidemirel — APPROVED** [review]

File: internal/initializer/crds_migrator.go [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+	crd.Status.StoredVersions = []string{storageVersion}
+	if err := kube.Status().Patch(ctx, &crd, client.MergeFrom(origCrd)); err != nil {
+		return errors.Wrapf(err, "couldn't update %s crd", c.crdName)
+	}
+
+	// One more check just to be sure we actually updated the crd
+	if err := kube.Get(ctx, client.ObjectKey{Name: c.crdName}, &crd); err != nil {
+		return errors.Wrapf(err, "cannot get %s crd to check", c.crdName)
+	}
+	if !sets.NewString(crd.Status.StoredVersions...).Has(storageVersion) {
```
Comment (turkenh) [inline internal/initializer/crds_migrator.go:107]: Shouldn't this check `StoredVersions` "only" has `storageVersion` ?

Comment (turkenh) [reply internal/initializer/crds_migrator.go:107]: Because otherwise, this check would pass without migration here.

**Review by turkenh — APPROVED** [review]

File: internal/initializer/crds_migrator.go (hunk 1 above)
Comment (phisco) [reply internal/initializer/crds_migrator.go:107]: done and tested again 👍

**Comment by turkenh** [comment]
There was a transient error with e2e testing, which was resolved with a retry.

File: internal/initializer/crds_migrator.go [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+		}
+		continueToken = resources.GetContinue()
+		if continueToken == "" {
+			break
+		}
+	}
+
+	origCrd := crd.DeepCopy()
+	crd.Status.StoredVersions = []string{storageVersion}
+	if err := kube.Status().Patch(ctx, &crd, client.MergeFrom(origCrd)); err != nil {
```
Comment (sttts) [inline internal/initializer/crds_migrator.go:99]: @phisco this must be `MergeFromWithOptions(origCrd, client.MergeFromWithOptimisticLock)`. Otherwise, we risk data loss.
