### PR TITLE
Fix composed resource names containing invalid characters

### LINKED ISSUE #6704: Composed resources shouldn't include composition resource names
### What happened?

We adopted a new deterministic approach to naming composed resources in https://github.com/crossplane/crossplane/pull/6630. I suggested we include the "composition resource name" in the name. The composition resource name is (these days) the unique name within the function pipeline's map of desired resources.

iirc the current format is like `<xr-name>-<xr-uid-segment>-<composition-resource-name>`.

Unfortunately not all composition resource names are valid Kubernetes `metadata.name` names. They could be uppercase, and include arbitrary characters.

For example this:

```kcl
_metadata = lambda name: str -> any {
    { annotations = { "krm.kcl.dev/composition-resource-name" = name }}
}
    rdsv1beta1.Instance{
        metadata: _metadata("RDSInstanceSmall")
```

Results in:

```
defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: cannot apply composed resource "RDSInstanceSmall" because it has an invalid name "rds-metrics-database-yury-bed2d7d17d59-RDSInstanceSmall". Must be a valid RFC 1123 subdomain name.
```

### How can we reproduce it?

Have a Composition function pipeline add an entry to the desired resources map, where the entry's key isn't a valid Kubernetes resource name. Try to use the Composition with an XR.

### What environment did it happen in?
Crossplane version: v2.0.0

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Fixes #6704

This PR addresses composed resource names that contain invalid Kubernetes  characters when composition resource names include uppercase letters,  periods, or other special characters that violate RFC 1123 subdomain rules.

The first commit switches from including composition resource names directly  in generated names to using a deterministic hash of the XR UID and  composition resource name. This ensures unique, valid names while avoiding
invalid characters from the composition resource name.

The second commit simplifies the naming implementation by consolidating hash generation within ChildName and adapting it specifically for Crossplane's constrained use case. The original implementation handled arbitrary suffix 
lengths that Crossplane doesn't encounter.

Examples of name generation changes:

**Invalid characters in composition resource name**:
- Old: `cool-resource-f4d3ac850155-Kid\!1` (invalid characters)
- New: `cool-resource-12d400e0a9a6` (valid hash)

**Long names with MD5 truncation**:
- Old: `very-long-name-f4d3ac850155-105d7597f637e83cc711605ac3ea4957-Kid\!1`
- New: `very-long-parent-name-very-long-parent-name-very-l-38ce86992a27`

All generated names now follow a consistent `<parentname>-<hash>` format and remain deterministic for the same XR and composition resource combination.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~ (not needed - internal naming change)
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~ (internal implementation detail)
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~ (not a backport candidate)
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~ (no API changes)

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: internal/names/names.go [hunk 1]
```diff
@@ -14,81 +14,54 @@ See the License for the specific language governing permissions and
...
+	hashLength = 12
 )
 
-var isAlphanumeric = regexp.MustCompile(`^[a-zA-Z0-9]*$`)
+// ChildName generates a name for a child resource based on the parent name, parent UID,
+// and child name. The result follows the format: <parentname>-<hash> where the hash
+// is derived from the parent UID and child name to ensure uniqueness.
+// If the parent name doesn't end with a hyphen, one is added before the hash.
+// If the full name would exceed Kubernetes' 63-character limit, the parent name
+// is truncated to fit.
```
Comment (negz) [inline internal/names/names.go:39]: CC @n3wscott FYI. I was having trouble wrapping my brain around ChildName. I think for the use case we have right now, this simpler version is sufficient.

**Comment by negz** [comment]
> is there a way to still include the composed resource name by default? e.g. try that and if it's invalid, then fall back to this approach that only uses a hash of it (plus other stuff)?

It would be nice, I don't love any of the options:

1. Try it and fall back to not including it
2. Proactively sanitize names to be compliant

Option 1 would require us to potentially make more calls to find a valid name. Option 2 could result in name conflicts (e.g. two different names sanitize to the same name), which we'd have to handle.

Given we've never included child resource names in the past, my preference is to stick with the simpler and more deterministic option.

**Review by jbw976 — APPROVED** [review]
this looks reasonable @negz given the downsides of trying to have a human readable name by default. Thank you!
