### PR TITLE
Required changes for crossplane-diff

### LINKED ISSUE #6341: Calling `beta validate` with `skipErrorLogs=true` fails even if validation passes
### What happened?
This is a [code bug](https://github.com/crossplane/crossplane/blob/01782c157210836cde79e62521392fcc3899dc9e/cmd/crank/beta/validate/validate.go#L137-L143) I found while working on another PR.

```go
if rf == 0 && !skipSuccessLogs {
	if _, err := fmt.Fprintf(w, "[✓] %s, %s validated successfully\n", r.GroupVersionKind().String(), getResourceName(r)); err != nil {
		return errors.Wrap(err, errWriteOutput)
	}
} else {
	failure++
}
```

What happens for the case where `rf` (failures) found is empty, and we *want to* skip success logs?

We fall through to the failure case.  The correct behavior would seem to be something like:

```go
if rf == 0 {
	if !skipSuccessLogs {
		if _, err := fmt.Fprintf(w, "[✓] %s, %s validated successfully\n", r.GroupVersionKind().String(), getResourceName(r)); err != nil {
			return errors.Wrap(err, errWriteOutput)
		}
	}
} else {
	failure++
}
```

### PR DESCRIPTION
**Pull request by jcogilvie**
### Description of your changes

Refactors and adds a few things to support `crossplane-contrib/crossplane-diff`.  

* adds Requirements to render outputs
* fixes validate bug re: output logging
* promotes and exposes internal components from `trace` and `validate` to support resource loading and xrm functions

Fixes #6341

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
~- [ ] Added or updated e2e tests.~
~- [ ] Linked a PR or a [docs tracking issue] to [document this change].~
~- [ ] Added `backport release-x.y` labels to auto-backport this PR.~
~- [ ] Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: cmd/crank/beta/trace/internal/printer/default.go [hunk 1]
```diff
@@ -31,8 +31,8 @@ import (
 	"github.com/crossplane/crossplane-runtime/pkg/fieldpath"
 
 	pkgv1 "github.com/crossplane/crossplane/apis/pkg/v1"
-	"github.com/crossplane/crossplane/cmd/crank/beta/trace/internal/resource"
-	"github.com/crossplane/crossplane/cmd/crank/beta/trace/internal/resource/xpkg"
+	"github.com/crossplane/crossplane/cmd/crank/util/resource"
```
Comment (negz) [inline cmd/crank/beta/trace/internal/printer/default.go]: I'd prefer to avoid adding a `util` package. They're considered an anti-pattern in Go.

See https://go.dev/wiki/CodeReviewComments#package-names.

File: cmd/crank/beta/validate/cmd.go [hunk 2]
```diff
@@ -40,7 +42,7 @@ type Cmd struct {
 	Resources  string `arg:"" help:"Resource sources as a comma-separated list of files, directories, or '-' for standard input."`
 
 	// Flags. Keep them in alphabetical order.
-	CacheDir              string `default:"~/.crossplane/cache"                                                       help:"Absolute path to the cache directory where downloaded schemas are stored." predictor:"directory"`
```
Comment (negz) [inline cmd/crank/beta/validate/cmd.go]: What does removing `predictor` do?

File: cmd/crank/beta/validate/validate.go [hunk 3]
```diff
@@ -133,17 +133,19 @@ func SchemaValidation(resources []*unstructured.Unstructured, crds []*extv1.Cust
...
 				if _, err := fmt.Fprintf(w, "[x] CEL validation error %s, %s : %s\n", r.GroupVersionKind().String(), getResourceName(r), e.Error()); err != nil {
 					return errors.Wrap(err, errWriteOutput)
 				}
 			}
 
-			if rf == 0 && !skipSuccessLogs {
-				if _, err := fmt.Fprintf(w, "[✓] %s, %s validated successfully\n", r.GroupVersionKind().String(), getResourceName(r)); err != nil {
-					return errors.Wrap(err, errWriteOutput)
+			if rf == 0 {
+				if !skipSuccessLogs {
```
Comment (negz) [inline cmd/crank/beta/validate/validate.go:155]: What's this change for? I think it's semantically identical right?

File: cmd/crank/beta/validate/validate_test.go [hunk 4]
```diff
@@ -1256,7 +1257,7 @@ func TestValidateResources(t *testing.T) {
 	for name, tc := range cases {
 		t.Run(name, func(t *testing.T) {
 			w := &bytes.Buffer{}
-			got := SchemaValidation(tc.args.resources, tc.args.crds, tc.args.errorOnMissingSchemas, false, w)
+			got := SchemaValidation(context.Background(), tc.args.resources, tc.args.crds, tc.args.errorOnMissingSchemas, false, w)
```
Comment (negz) [inline cmd/crank/beta/validate/validate_test.go]: Nit: typically we'd add `tc.args.ctx` and pass that, like the other args. Usually we just leave it `nil` (unspecified) in tests.

File: cmd/crank/render/render.go [hunk 5]
```diff
@@ -81,10 +81,16 @@ type Inputs struct {
 
 // Outputs contains all outputs from the render process.
 type Outputs struct {
+	// the rendered xr
 	CompositeResource *ucomposite.Unstructured
+	// the rendered mrs derived from the xr
```
Comment (negz) [inline cmd/crank/render/render.go]: Nit: These won't always be MRs.

Also, I'd prefer comments to use proper grammar (caps, punctuation etc).

File: cmd/crank/render/render.go [hunk 6]
```diff
@@ -81,10 +81,16 @@ type Inputs struct {
...
 	ComposedResources []composed.Unstructured
-	Results           []unstructured.Unstructured
-	Context           *unstructured.Unstructured
+	// the Function results (not render results)
+	Results []unstructured.Unstructured
+	// the Crossplane context object
+	Context *unstructured.Unstructured
+	// the Function requirements
+	Requirements map[string]fnv1.Requirements
```
Comment (negz) [inline cmd/crank/render/render.go]: The ship has probably already sailed here but I don't love that render now outputs:

1. Actual composed resources
2. A bunch of things that look like composed resources but aren't (results, context, now also requirements)

It makes me wonder whether render should have two modes:

1. Output a YAML stream of the changes it'd make to resources - i.e. XR status, composed resource spec
2. Just dump the whole `RunFunctionResponse` as YAML

File: cmd/crank/render/render.go [hunk 7]
```diff
@@ -394,7 +407,13 @@ func Render(ctx context.Context, log logging.Logger, in Inputs) (Outputs, error)
 //
 // https://github.com/crossplane/crossplane/blob/0965f0/internal/controller/apiextensions/composite/composition_render.go#L117
 func SetComposedResourceMetadata(cd resource.Object, xr resource.LegacyComposite, name string) error {
-	cd.SetGenerateName(xr.GetName() + "-")
+
+	// We recommend composed resources let us generate a name for them. They'reAdd commentMore actions
+	// allowed to explicitly specify a name if they want though.
```
Comment (negz) [inline cmd/crank/render/render.go]: This comment looks wonky.

File: cmd/crank/util/loader/loader.go [hunk 8]
```diff
@@ -14,7 +14,8 @@ See the License for the specific language governing permissions and
 limitations under the License.
 */
 
-package validate
+// Package loader provides functionality to load Kubernetes manifests from various sources
+package loader
```
Comment (negz) [inline cmd/crank/util/loader/loader.go]: Would `load` make sense for this package name?

I could then imagine callers calling e.g. `load.YAMLStream()`

File: cmd/crank/util/resource/xrm/client_test.go [hunk 9]
```diff
@@ -26,11 +26,11 @@ import (
 	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
 
 	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
-
 	"github.com/crossplane/crossplane-runtime/pkg/resource/unstructured/claim"
 	"github.com/crossplane/crossplane-runtime/pkg/resource/unstructured/composite"
 	"github.com/crossplane/crossplane-runtime/pkg/resource/unstructured/reference"
-	resource2 "github.com/crossplane/crossplane/cmd/crank/beta/trace/internal/resource"
+
+	resource2 "github.com/crossplane/crossplane/cmd/crank/util/resource"
```
Comment (negz) [inline cmd/crank/util/resource/xrm/client_test.go]: Why is this `resource2`? 🤔

File: test/e2e/config/environment.go [hunk 10]
```diff
@@ -145,6 +147,11 @@ func (e *Environment) GetKindClusterName() string {
 	return *e.kindClusterName
 }
 
+// GetCrossplaneImage returns the image to use when running crossplane for these tests.Add commentMore actions.
```
Comment (negz) [inline test/e2e/config/environment.go]: This comment looks mangled too.

File: cmd/crank/beta/trace/internal/printer/default.go (hunk 1 above)
Comment (jcogilvie) [reply cmd/crank/beta/trace/internal/printer/default.go]: This PR lifts a few shared utilities upward for the purposes of sharing them, but you advised me against adding `pkg`, and we don't expect anybody to call them except for derivative CLI plugins.  

Any suggestions on what to do instead?  I would move them `internal` if we weren't trying to decompose this into other repos.  The current package structure mirrors the command structure and suggests "one directory per subcommand," so where does the ancillary shared stuff go?

File: cmd/crank/beta/validate/validate.go (hunk 3 above)
Comment (jcogilvie) [reply cmd/crank/beta/validate/validate.go:155]: No, it's the fix for [this bug](https://github.com/crossplane/crossplane/issues/6341).

File: cmd/crank/render/render.go (hunk 7 above)
Comment (jcogilvie) [reply cmd/crank/render/render.go]: I probably copied this out of the github page of another commit.  Fixing.

File: cmd/crank/beta/validate/cmd.go (hunk 2 above)
Comment (jcogilvie) [reply cmd/crank/beta/validate/cmd.go]: I think this was a merge snafu.  Adding it back.

File: cmd/crank/beta/validate/validate_test.go (hunk 4 above)
Comment (jcogilvie) [reply cmd/crank/beta/validate/validate_test.go]: I can add it on the `tc` but I was leaving room for 1.24's `t.Context`:  https://pkg.go.dev/testing#T.Context, not that it matters very much here.

File: cmd/crank/util/loader/loader.go (hunk 8 above)
Comment (jcogilvie) [reply cmd/crank/util/loader/loader.go]: Done.

File: cmd/crank/beta/trace/internal/printer/default.go (hunk 1 above)
Comment (jcogilvie) [reply cmd/crank/beta/trace/internal/printer/default.go]: Went with `foundation` for now.

File: cmd/crank/render/render.go [hunk 11]
```diff
@@ -412,7 +425,12 @@ func Render(ctx context.Context, log logging.Logger, in Inputs) (Outputs, error)
 //
 // https://github.com/crossplane/crossplane/blob/0965f0/internal/controller/apiextensions/composite/composition_render.go#L117
 func SetComposedResourceMetadata(cd resource.Object, xr resource.LegacyComposite, name string) error {
-	cd.SetGenerateName(xr.GetName() + "-")
+	// We recommend composed resources let us generate a name for them. They're
+	// allowed to explicitly specify a name if they want though.
+	if cd.GetName() == "" && cd.GetGenerateName() == "" {
```
Comment (jcogilvie) [inline cmd/crank/render/render.go:432]: I made this change based on [this change](https://github.com/crossplane/crossplane/commit/02fdd6848fa2fe55a5ed0d9d224487d5b98c4789) to bring render closer to the actual controller.

File: internal/controller/apiextensions/composite/composition_functions.go [hunk 12]
```diff
@@ -436,6 +436,7 @@ func (c *FunctionComposer) Compose(ctx context.Context, xr *composite.Unstructur
 		if ok {
 			cd.SetNamespace(or.Resource.GetNamespace())
 			cd.SetName(or.Resource.GetName())
+			cd.SetGenerateName(or.Resource.GetGenerateName())
```
Comment (turkenh) [inline internal/controller/apiextensions/composite/composition_functions.go:440]: Is this intentional? Doesn't look related for the rest of the PR 🤔

File: cmd/crank/foundation/util.go [hunk 13]
```diff
@@ -0,0 +1,70 @@
+// Package foundation is for functions and helpers shared between components that can be exported to things like crossplane-contrib.
+package foundation
```
Comment (turkenh) [inline cmd/crank/foundation/util.go]: I am aware of the other discussion regarding the naming of this package, but "foundation" didn't resonate me TBH. How about `common` or `shared` ?

File: cmd/crank/foundation/loggerwriter/logger_writer.go [hunk 14]
```diff
@@ -0,0 +1,38 @@
...
+	message := strings.TrimSuffix(string(p), "\n")
+	if message != "" {
+		w.logger.Debug(message)
+	}
+	return len(p), nil
+}
+
+// WithLevel allows setting a specific logging level.
+func (w *LoggerWriter) WithLevel(level int) *LoggerWriter {
+	w.level = level
```
Comment (turkenh) [inline cmd/crank/foundation/loggerwriter/logger_writer.go]: Is this level used at all?

File: cmd/crank/foundation/util.go [hunk 15]
```diff
@@ -0,0 +1,70 @@
+// Package foundation is for functions and helpers shared between components that can be exported to things like crossplane-contrib.
```
Comment (turkenh) [inline cmd/crank/foundation/util.go]: nit: may be something like

```suggestion
// Package foundation provides functions and helpers shared between CLI utilities, available for import by external tools interacting with Crossplane.
```

**Review by turkenh — APPROVED** [review]
Left a few commands but overall looking good to me. @jcogilvie thanks for your efforts here 🙌

**Comment by turkenh** [comment]
I approved the PR but still wondering whether we should wait until right after we branch out for v2.0 for merging. The reason it might make sense to wait is that these changes don't actually change CLI/Crossplane behavior, they just make the helpers importable by external tools, hence no need to rush for release. 

It should be fine to wait a couple of days and merge right after branching out, since external tools can still consume from main without blocking others too much.

File: cmd/crank/foundation/loggerwriter/logger_writer.go (hunk 14 above)
Comment (jbw976) [reply cmd/crank/foundation/loggerwriter/logger_writer.go]: or is this `LoggerWriter` typed used anywhere - I couldn't find any references to it. Do we need to add this here?

File: cmd/crank/foundation/resource/xrm/client.go [hunk 16]
```diff
@@ -115,34 +117,58 @@ func getResourceChildrenRefs(r *resource.Resource, getConnectionSecrets bool) []
...
+		checkLegacyField := fieldpath.Pave(obj.Object).GetValueInto("spec.resourceRef", out)
+		if checkNewField == nil || checkLegacyField == nil {
+			xrc := claim.Unstructured{Unstructured: obj}
+			if ref := xrc.GetResourceReference(); ref != nil {
+				refs = append(refs, v1.ObjectReference{
+					APIVersion: ref.APIVersion,
+					Kind:       ref.Kind,
+					Name:       ref.Name,
+				})
+			}
```
Comment (jbw976) [inline cmd/crank/foundation/resource/xrm/client.go]: this is odd - it seems to be the exact same changes that I reviewed earlier today (and think we should do differently) from @man-ish-k in https://github.com/crossplane/crossplane/pull/6549/files - how did this code end up in your PR too? it's from another contributor/fork, so I can't immediately blame a bad merge. Do you know how this happened? 🤔

File: cmd/crank/foundation/util.go (hunk 13 above)
Comment (jbw976) [reply cmd/crank/foundation/util.go]: +1, i've seen us use `common` in other crossplane projects, that is reasonable to me.

Comment (jbw976) [reply cmd/crank/foundation/util.go]: and then, is there a better child package this functionality could go in? maybe `common/crd`?

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 12 above)
Comment (jbw976) [reply internal/controller/apiextensions/composite/composition_functions.go:440]: i see a new e2e test check for this behavior in `TestBasicCompositionCluster`, but I don't see it mentioned in the PR description or a mention of a tracking issue. Can you help link this up for us @jcogilvie?

**Review by jbw976 — CHANGES_REQUESTED** [review]
@turkenh there are a couple behavioral changes in this PR in addition to just exposing some of the crossplane CLI internals, so if this PR is of sufficient quality then we can go ahead and merge before v2 code freeze. That being said, there are some questions that have come up about unexpected behavioral changes and unexpected code (e.g. the mystery`crossplane beta trace` changes, so let's get those resolved before merging either way 😇

File: internal/controller/apiextensions/composite/composition_functions.go (hunk 12 above)
Comment (jcogilvie) [reply internal/controller/apiextensions/composite/composition_functions.go:440]: This fixes a regression introduced in v2 that I noticed while writing `diff`.  The e2e I added should already pass on v1, but it fails on v2 without this change.  There's no ticket because the regression hasn't made it into a release afaik.

```
		// If this desired resource state pertains to an existing composed
		// resource we want to maintain its name and namespace.
```

Now we'll propagate the `generateName` field, if it exists, too, even in the presence of an actual supplied name.  The `name` field wins, but we shouldn't probably make unanticipated changes to these objects (like stripping `generateName`).

File: cmd/crank/foundation/resource/xrm/client.go (hunk 16 above)
Comment (jcogilvie) [reply cmd/crank/foundation/resource/xrm/client.go]: I fixed it first, made the change independently -- this PR has been open a long time.  If it's on main now, it probably just needs a rebase?

Comment (jbw976) [reply cmd/crank/foundation/resource/xrm/client.go]: It looks like @man-ish-k made the change in an earlier PR before this one in https://github.com/crossplane/crossplane/pull/6380, then closed that to open https://github.com/crossplane/crossplane/pull/6549 that was merged recently.

Do you all work together or know each other? I'm still not understanding how this duplication happened exactly and I definitely would like to 🙏

Comment (jbw976) [reply cmd/crank/foundation/resource/xrm/client.go]: synced with @jcogilvie in DMs to investigate this a bit further - this appears to be an artifact of async collaboration and overlap while tackling the same issue as opposed to anything malicious. they were both independently working on solutions for this and feedback was exchanged on PRs. @jcogilvie pulled an earlier attempt from @man-ish-k into his branch to try some fixes on it and now that isn't showing up well in git history after some commit squashing.

Thanks for taking the time to clear this up folks! 🙇‍♂️

Comment (jcogilvie) [reply cmd/crank/foundation/resource/xrm/client.go]: We do not work together, no.

Without digging into it too deeply I'm pretty sure they made the initial fix, I provided feedback on their PR and fixed their fix with said feedback locally, and then assumed git would handle it when everything got merged.  They ended up with a separate PR and that probably messed with the commits I pulled -- though I figured that should come out in the wash with the commit history shenanigans I did here upon request.

File: cmd/crank/foundation/loggerwriter/logger_writer.go (hunk 14 above)
Comment (jcogilvie) [reply cmd/crank/foundation/loggerwriter/logger_writer.go]: The scope of this `foundation` (soon to be `crank/common`) library will include possibly-locally-unused objects if they have value for downstream CLI plugins.  This one serves as an adapter between `logging.Logger` and the `validate.SchemaValidation` method that takes an `io.Writer` for output.  

I figured it had more value in the common place than internally in `diff`.
