### PR TITLE
define an API promotion process

### LINKED ISSUE #5932: Proposal for n +/- 1 safe upgrade and downgrade between releases with CRD changes
### What problem are you facing?

Downgrading crossplane 1.17 to 1.16 does not work, starting 1.16 fails with the following error:

```
crossplane: error: cannot initialize core: cannot apply crd: cannot patch object: CustomResourceDefinition.apiextensions.k8s.io "functionrevisions.pkg.crossplane.io" is invalid: status.storedVersions[1]: Invalid value: "v1": must appear in spec.versions
```

This is because 1.17 introduces v1 _and_ switches the stored version to v1 in the same release. Downgrading the CRD is not allowed. Crossplane attempts to apply CRDs on startup.

The ability to downgrade without any manual steps and thinking increases the usability of crossplane and reduces friction, planning for anyone operating it.

### How could Crossplane help solve your problem?

I propose that the next time a similar change is done, we attempt to find a process which allows downgrades.

#### Alternative A: We could split such changes over two releases:

1.16: v1beta1 stored and served
1.17: v1beta1 stored and served, v1 served
1.18: v1beta1 served, v1 stored and served

I created a small and currently incomplete lab to test the idea here:
https://github.com/chlunde/crd-lab

#### Alternative B: Don't attempt to downgrade CRDs

Maybe we could update crossplane to not attempt to downgrade CRDs on startup. This would be a smaller change.

#### Alternative C: Add v1 to the n-1 version

This would require an extra release 1.16.2 with v1beta1 stored and served, v1 served. This is something like what karpenter did, but they also changed the API and introduced conversion webhooks: https://karpenter.sh/docs/upgrading/v1-migration/#upgrade-procedure

Related milestone: https://github.com/crossplane/crossplane/issues/4372

### PR DESCRIPTION
**Pull request by jbw976**
### Description of your changes

This PR defines a process for promoting APIs in Crossplane in order to be able to safely upgrade and downgrade across all versions.  This process is in the form of a contributor guide and a link has been added to the PR checklist to remind contributors if they are adding/removing/promoting an API then they should follow this process.

This process was originally proposed/discussed in https://github.com/crossplane/crossplane/pull/6157#pullrequestreview-2482652310.

This PR also adds a migrator for the Usage API being promoted to Beta that was missed. The need for this migrator was discussed in https://github.com/crossplane/crossplane/pull/6175#pullrequestreview-2502835976.

Fixes #5932

### How has this change been tested?

I've gone through the entire upgrade and downgrade process across 4 versions as described in the proposed process. The details of how this testing was performed and the results observed can be found in this gist:
https://gist.github.com/jbw976/276a088a2cd0f3c1e99b5f7cd074124a

TL;DR: An alpha `Usage` resource was created on v1.18 and then Crossplane was upgraded to realistic, but not yet released, upcoming versions v1.19 -> v1.20 -> v1.21 to exercise the entire promotion workflow process. Then Crossplane was downgraded from v1.21 -> v1.20 -> v1.19 -> v1.18. The health of Crossplane and the state of the `Usage` CRD was verified at every version and no undesired behavior was observed.

The realistic changes used during testing that continue the `Usage` promotion workflow in not yet released versions of Crossplane can be seen in:
* v1.20: https://github.com/crossplane/crossplane/compare/main...jbw976:crossplane:crossplane-usages-1.20
* v1.21: https://github.com/crossplane/crossplane/compare/main...jbw976:crossplane:crossplane-usages-1.21

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet

### CODE REVIEW

File: cmd/crossplane/core/init.go [hunk 1]
```diff
@@ -97,6 +92,17 @@ func (c *initCommand) Run(s *runtime.Scheme, log logging.Logger) error {
 		)
 	}
 
+	// CRD migrator steps are done after core CRDs are applied/updated, so we
+	// are always migrating to the most current storage version
+	steps = append(steps,
+		initializer.NewCoreCRDsMigrator("compositionrevisions.apiextensions.crossplane.io", "v1alpha1"),
+		initializer.NewCoreCRDsMigrator("environmentconfigs.apiextensions.crossplane.io", "v1beta1"),
+		initializer.NewCoreCRDsMigrator("usages.apiextensions.crossplane.io", "v1beta1"),
```
Comment (jbw976) [inline cmd/crossplane/core/init.go:100]: also note that this Usages migrator was added within this moved migrator steps block. https://github.com/crossplane/crossplane/pull/6226/commits/773c40947e0bfbc769f98e7470dbc12899f96a4e shows that addition in isolation.

**Comment by jbw976** [comment]
I have been working with @phisco and @turkenh on this API promotion process, but @sttts your opinion is particularly valuable here too 😉

File: contributing/guide-api-promotion.md [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+An explanation of Crossplane's feature lifecycle can be found in the [Feature
+Lifecycle] docs page.
+
+## Core Issue
+
+The root cause we have encountered in past problematic API promotions is that we
+try to drop a particular version from a CRD while there may still be resources
+of that version stored in etcd. Kubernetes does not allow this action because it
+can result in possible data loss.
```
Comment (sttts) [inline contributing/guide-api-promotion.md:17]: It allows it. But it's protected by `status.storedVersions`. It needs somebody to remove a version from that slice AFTER cleaning up etcd from old instances.

File: contributing/guide-api-promotion.md [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+   updated to Beta in the same release
+1. User installs this new Crossplane version and creates a Beta resource that is
+   stored in etcd as Beta
+1. User downgrades to the previous Crossplane version where the CRD's Beta
+   version did not exist
+1. The Crossplane init container tries to update the CRD back to the Alpha
+   version, which drops the Beta version
+1. The Kubernetes API server rejects this action because there are still Beta
+   resources stored in etcd according to the CRD's [`status.storedVersions`]
+   field
```
Comment (sttts) [inline contributing/guide-api-promotion.md:32]:
```suggestion
1. The Kubernetes API server rejects this action because there might be still Beta
   resources stored in etcd according to the CRD's [`status.storedVersions`]
   field
```

Comment (sttts) [reply contributing/guide-api-promotion.md:32]: "it doesn't know better"

**Comment by sttts** [comment]
Just some nits about the `CRD.status.storedVersions`. This does not tell whether there are really those objects. It just says that there might be because a version was storage version at some point in time. Whether there is an object left in etcd you can only know by touching all of them once. The apiserver will rewrite. After that process you can update `CRD.status.storedVersions`.

**Comment by jbw976** [comment]
Awesome, thank you for taking a look @sttts and sharing your expertise!! i'll push your wording suggestion when github is healthy again - git operations are down now according to https://www.githubstatus.com/ 🙄 

>  Whether there is an object left in etcd you can only know by touching all of them once. The apiserver will rewrite. After that process you can update CRD.status.storedVersions.

this perfectly agrees with my understanding of what https://github.com/crossplane/crossplane/blob/main/internal/initializer/crds_migrator.go#L49 does 🤓

**Review by phisco — APPROVED** [review]
Thanks @jbw976, modulo the wording changes suggested by @sttts, this LGTM!
