### PR TITLE
fix(crank): beta validate properly pulling crossplane image

### LINKED ISSUE #6051: `validate` fails to download crossplane image
### What happened?

While trying out the functionality from this PR:

* https://github.com/crossplane/crossplane/pull/5890
 
on the new [v1.18.0-rc.1](https://github.com/crossplane/crossplane/releases/tag/v1.18.0-rc.1) build, I encountered the following error:

```
❯ crossplane beta validate crossplane.yaml composition.yaml
schemas does not exist, downloading:  xpkg.upbound.io/crossplane/crossplane:v1.18.0-rc.1
crossplane: error: cannot download and load cache: cannot cache package dependencies: cannot download package xpkg.upbound.io/crossplane/crossplane:v1.18.0-rc.1: no base layer found for image xpkg.upbound.io/crossplane/crossplane:v1.18.0-rc.1
```

I first thought this had to do with `v1.18.0-rc.1` being a RC pre-release build, but this behavior reproduces with an official release version of Crossplane also:
```
❯ crossplane beta validate crossplane.yaml composition.yaml --crossplane-image=xpkg.upbound.io/crossplane/crossplane:v1.17.0
schemas does not exist, downloading:  xpkg.upbound.io/crossplane/crossplane:v1.17.0
crossplane: error: cannot download and load cache: cannot cache package dependencies: cannot download package xpkg.upbound.io/crossplane/crossplane:v1.17.0: no base layer found for image xpkg.upbound.io/crossplane/crossplane:v1.17.0
```

It looks like `crossplane beta validate` doesn't work at all because even if you don't request a `--crossplane-image`, it will still try to download the Crossplane version matching the `crossplane` binary, and it fails 100% of the time for me.

### How can we reproduce it?

Install Crossplane `v1.18.0-rc.1`, e.g.:
```
curl -sL https://raw.githubusercontent.com/crossplane/crossplane/v1.18.0-rc.1/install.sh | XP_VERSION=v1.18.0-rc.1 sh
```

Then use @haarchri testing examples:
```
git clone https://github.com/haarchri/xp-validate-test-cases.git
cd xp-validate-test-cases/pat
crossplane beta validate crossplane.yaml composition.yaml
```

### What environment did it happen in?
Crossplane version: `v1.18.0-rc.1`

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/6051

Missed implementing the `Is` method to get `IsErrBaseLayerNotFound` to work as expected... Moved to use `errors.As` directly.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet

### CODE REVIEW

File: cmd/crank/beta/validate/image.go [hunk 1]
```diff
@@ -72,6 +72,12 @@ type ErrBaseLayerNotFound struct {
 	error
 }
 
+// Is implements the errors.Is interface.
+func (e *ErrBaseLayerNotFound) Is(target error) bool {
```
Comment (jbw976) [inline cmd/crank/beta/validate/image.go:76]: can you help me understand why we need to implement this function? why exactly doesn't the standard `errors.Is()` work already for us? 🤔 

when quickly searching, i wasn't finding too many examples of other folks needing to do this. thanks for the explanation!

Comment (phisco) [reply cmd/crank/beta/validate/image.go:76]: Yeah, not the most idiomatic code. I should be using errors.As directly from the IsErrBaseLayerNotFound.

**Review by jbw976 — APPROVED** [review]
Cool, this looks good @phisco! I was able to test the broken scenario described in #6051  and it works successfully now to download the Crossplane and function schemas and output the validation errors:
```
❯ crank beta validate crossplane.yaml composition.yaml
schemas does not exist, downloading:  xpkg.upbound.io/crossplane/crossplane:v1.17.0
[x] schema validation error pt.fn.crossplane.io/v1beta1, Kind=Resources,  : resources[0].name: Required value
[x] schema validation error pt.fn.crossplane.io/v1beta1, Kind=Resources,  : patches: Invalid value: "patches": unknown field: "patches"
[x] schema validation error pt.fn.crossplane.io/v1beta1, Kind=Resources,  : resources[0].name: Required value
[✓] apiextensions.crossplane.io/v1, Kind=Composition, pat.xkarpenters.aws.platform.upbound.io validated successfully
Total 2 resources: 0 missing schemas, 0 success cases, 2 failure cases
crossplane: error: cannot validate resources: could not validate all resources
```

It looks like there is a duplicated error message in that output and the count of success/failure looks off, but the regression preventing `validate` from working at all appears to be fixed.  I'll open a tracking issue for those minor issues, but wouldn't block v1.18 on them.

edit: opened https://github.com/crossplane/crossplane/issues/6057 to track

**Comment by jbw976** [comment]
ah darn, there's a linter error here now too @phisco: https://github.com/crossplane/crossplane/actions/runs/11640854333/job/32418684683?pr=6053

```
+go-lint *failed* | cmd/crank/beta/validate/image.go:71:6: the type name `ErrBaseLayerNotFound` should conform to the `XxxError` format (errname)
+go-lint *failed* | type ErrBaseLayerNotFound struct {
```
