### PR TITLE
Accept version changes in composed templates

### LINKED ISSUE #5368: Cannot change the version of a composed resource in the default `Resources` mode
### What happened?

We started seeing multiple multiple versions of managed resources, e.g. provider-kubernetes `Object` `v1alpha2`. While conversions between versions are automated at Kubernetes level, we expect users to bump the resource manifests in their compositions. However, composite resources fail with the following error when this is done on an existing composite resource:

```shell
  Warning  ComposeResources         14s (x5 over 23s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: cannot parse base template of composed resource "nop-resource-1": cannot change the kind of a composed resource from kubernetes.crossplane.io/v1alpha1, Kind=Object to kubernetes.crossplane.io/v1alpha2, Kind=Object (possible composed resource template mismatch)
```

### How can we reproduce it?

See https://github.com/turkenh/repro-xp-5368

### What environment did it happen in?
Crossplane version: v1.14.5

### PR DESCRIPTION
**Pull request by turkenh**
### Description of your changes

This PR fixes the linked issue where composite controller erroring out when the version of a composed resource updated in the composition. This is a valid use case and we will see this more with the introduction of multi-versioned managed resources in the provider ecosystem.

Prior to v1.14, we were [only checking kind](https://github.com/crossplane/crossplane/blob/cb232d32a595876a98ab3a7f5125e3fa26e2f2ac/internal/controller/apiextensions/composite/composition_pt.go#L512), however, with [this PR](https://github.com/crossplane/crossplane/pull/4500), we started checking all GVK. I believe, we should rather check Group and Kind, and accept changes in the version. 

Fixes #5368

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [x] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

File: internal/controller/apiextensions/composite/composition_render.go [hunk 1]
```diff
@@ -61,13 +61,16 @@ func RenderFromJSON(o resource.Object, data []byte) error {
...
-	// template (e.g. because the order of an array of anonymous templates
+	// someone changed the kind or group in the template, or we're trying to use the
+	// wrong template (e.g. because the order of an array of anonymous templates
 	// changed).
-	if !gvk.Empty() && o.GetObjectKind().GroupVersionKind() != gvk {
-		return errors.Errorf(errFmtKindChanged, gvk, o.GetObjectKind().GroupVersionKind())
+	// Please note, we don't check for version changes, as versions can change. For example,
+	// if a composed resource was created with a template that has a version of "v1alpha1",
+	// and then the template is updated to "v1beta1", the composed resource will still be valid.
+	if !gvk.Empty() && o.GetObjectKind().GroupVersionKind().GroupKind() != gvk.GroupKind() {
```
Comment (phisco) [inline internal/controller/apiextensions/composite/composition_render.go:72]: I wonder if we could go back to only checking "Kind." I could see checking the group backfiring during future migrations.

**Review by phisco — APPROVED** [review]
Thanks @turkenh!

File: internal/controller/apiextensions/composite/composition_render.go (hunk 1 above)
Comment (turkenh) [reply internal/controller/apiextensions/composite/composition_render.go:72]: I am not sure, if a migration requires a change in `Group`, it could very well require a change in `Kind` as well. `Version` differentiates here. 
I would imagine a migration tool updating references in such a case, rather than trying to accept here.

Comment (phisco) [reply internal/controller/apiextensions/composite/composition_render.go:72]: yeah, sounds reasonable, I was just considering it given that it was the original behaviour

**Comment by phisco** [comment]
Regarding `function-patch-and-transform` this doesn't apply because we always get an empty `gvk` [there](https://github.com/crossplane-contrib/function-patch-and-transform/blob/0d695806eb273a377abb9219abef2a768d906b99/render.go#L44) because it gets only created [here](https://github.com/crossplane-contrib/function-patch-and-transform/blob/0d695806eb273a377abb9219abef2a768d906b99/fn.go#L140), afaict

**Comment by turkenh** [comment]
> Nevertheless, I'll open a PR there after this is merged to be consistent.

https://github.com/crossplane-contrib/function-patch-and-transform/pull/88
