### PR TITLE
crank render: fix XR matchLabels validation in composition

### LINKED ISSUE #5860: `render` should check if XR's `matchLabels` have corresponding label at composition
### What problem are you facing?

`matchLabels` provides a useful interface for [composition selection](https://docs.crossplane.io/latest/concepts/composite-resources/#composition-selection) using the `compositionSelector` of XRs. Currently at `beta render` when we render resources we don’t check if the `matchLabels` section of XR’s `compositionSelector` has a correspondent label at the composition itself. This can result with a creation of an XR that does not point to any composition (due to a typo or another reason) in the cluster and therefore wouldn’t work, yet still works okay during render.

Here is a sample gist showing this behavior: https://gist.github.com/enesonus/7e019d8b7276e0aeed609de99cbfeb00 

Checking the validity of the `matchLabels` at render time and giving proper errors/warnings would help users detect possible problems with the composition or XR and shift the validation process more to the left.

Currently we have some validation mechanisms that perform logical validation of a Composition: 
https://github.com/crossplane/crossplane/blob/52d3a7e730b70287863bf4092791f2bc742a35a9/cmd/crank/beta/render/cmd.go#L135

These validations do not do any validations for cross-resource referencing.

### How could Crossplane help solve your problem?

Crossplane can solve this problem by adding validation checks during the rendering process to ensure that the `matchLabels` specified in a composite resource's `compositionSelector` have corresponding labels in the target composition's metadata. 

This validation would prevent the creation of composite resources that do not match any composition due to typos or missing labels, thus providing users with immediate feedback and reducing configuration errors.

### PR DESCRIPTION
**Pull request by omerap12**
### Description of your changes

Fixes #5860 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
~~- [ ] Added or updated unit tests.~~
~~- [ ] Added or updated e2e tests.~~
- [x] Linked a PR or a [docs tracking issue] to [document this change].
~~- [ ] Added `backport release-x.y` labels to auto-backport this PR.~~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet

### CODE REVIEW

File: cmd/crank/render/cmd.go [hunk 1]
```diff
@@ -150,6 +150,22 @@ func (c *Cmd) Run(k *kong.Context, log logging.Logger) error { //nolint:gocognit
...
 
+	// check if XR's matchLabels have corresponding label at composition
+	xrSelector := xr.GetCompositionSelector()
+	if xrSelector != nil {
+		for key, value := range xrSelector.MatchLabels {
+			compValue, exists := comp.Labels[key]
+			if !exists {
+				return fmt.Errorf("composition %q is missing required label %q", comp.GetName(), key)
+			}
+			fmt.Println("compValue: ", compValue, "value: ", value)
```
Comment (phisco) [inline cmd/crank/render/cmd.go:161]:
```suggestion
```

**Review by phisco — APPROVED** [review]
Thanks!
