### PR TITLE
fix: ensure enforcedCompositionRef properly controls composition selection

### LINKED ISSUE #6230: `enforcedCompositionRef` conflicting with Claim/Composite sync
### What happened?

We are starting using the `enforcedCompositionRef` feature to migrate from a multiple-composition-per-API to a one-compoistion-per-API setup.

While testing we found to 2 major problems with the behaviour of that parameter:

1. after updating an XRD with added  `enforcedCompositionRef`, this only takes effect after a Crossplane Pod restart
2. the Claim/Composite sync (CSA, not tested with SSA alpha feature) is conflicting with `enforcedCompositionRef`  for the setting of `compositionRef`.
   * this results in Claims/Composites with this:
      ```
      spec:
        claimRef:
          apiVersion: cluster/v1alpha1
          kind: NodePool
          name: tenant-nodepool
          namespace: tenant
        compositionRef:
          name: node-pool-iat
        compositionRevisionRef:
          name: node-pool-34014e3
        compositionSelector:
          matchLabels:
            stage: iat
        compositionUpdatePolicy: Automatic
      ``` 
   * in the events of the XR we see the CompositionSelection-loop (increasing loop interval) :
      ```
      Events:
        Type    Reason                Age                From                                                             Message
        ----    ------                ----               ----                                                             -------
        Normal  CompositionSelection  17m (x2 over 53m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Enforced composition has been selected
        Normal  ComposeResources      9m18s              defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully composed resources
      ```
   * sometimes (e.g. in k9s) you can catch the flicker where shortly `compositionRef` has the desired Composition name
   * however the `compositionRevisionRef` seems to never change.
   * also it is possible to delete the old Composition (here "node-pool-iat"), because none of its CompositionRevision is in use
   * Note: in cases/APIs where there is only a Composite (no Claim, e.g. composed via other Composition), we do not see this behaviour 

### How can we reproduce it?

1. base setup: 
   * XRD (without `enforcedCompositionRef`)
   * 2 Compositions (A + B) for that API
   * 1 deployed test Claim that references composition A (directly `compositionRef` or via `compositionSelector`)
2. update the XRD with an enforcedCompositionRef for composition B
3. trigger manually (or wait) for Crossplane Pod restart
4. look at XRC/XR spec and XR Events (as seen in the examples above)

### What environment did it happen in?
Crossplane version: 1.17.1

### PR DESCRIPTION
**Pull request by ezgidemirel**
### Description of your changes

This PR fixes an issue where the `enforcedCompositionRef` field in XRDs was not working as expected. Although composites and claims appeared to reference the correct `compositionRevisionRef`, their `compositionRef` fields were incorrect or out of sync.

Testing instructions can be found in #6867 

Fixes #6230 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [x] Added `backport release-x.y` labels to auto-backport this PR.
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

File: internal/controller/apiextensions/claim/syncer_csa.go [hunk 1]
```diff
@@ -191,6 +195,24 @@ func (s *ClientSideCompositeSyncer) Sync(ctx context.Context, cm *claim.Unstruct
...
 
+	// Propagate composition ref from the XR if the claim doesn't have an
+	// opinion. Composition and revision selectors only propagate from claim ->
+	// XR. When a claim has selectors **and no reference** the flow should be:
+	//
+	// 1. Claim controller propagates selectors claim -> XR.
+	// 2. XR controller uses selectors to set XR's composition ref.
+	// 3. Claim controller propagates ref XR -> claim.
+	//
+	// When a claim sets a composition ref, it supercedes selectors. It should
```
Comment (phisco) [inline internal/controller/apiextensions/claim/syncer_csa.go]: typo:
```suggestion
	// When a claim sets a composition ref, it supersedes selectors. It should
```

File: internal/controller/apiextensions/claim/syncer_csa_test.go [hunk 2]
```diff
@@ -398,7 +398,7 @@ func TestClientSideSync(t *testing.T) {
 	for name, tc := range cases {
 		t.Run(name, func(t *testing.T) {
 			s := NewClientSideCompositeSyncer(tc.params.c, tc.params.ng)
-			err := s.Sync(tc.args.ctx, tc.args.cm, tc.args.xr)
+			err := s.Sync(tc.args.ctx, tc.args.cm, tc.args.xr, false)
```
Comment (phisco) [inline internal/controller/apiextensions/claim/syncer_csa_test.go:401]: Ideally we could test this for true here too as we do for ssa, but afaict they touch the same codepaths, so fine.

File: internal/controller/apiextensions/claim/indexes.go [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+
+	v1 "github.com/crossplane/crossplane/v2/apis/apiextensions/v1"
+)
+
+// XRDByCompositeGVKIndex is the name of an index that indexes XRDs by their
+// composite GVK. This allows us to quickly look up the XRD for a given composite resource.
+func XRDByCompositeGVKIndex() string {
+	return "xrdByCompositeGVK"
+}
+
```
Comment (phisco) [inline internal/controller/apiextensions/claim/indexes.go:35]: nit: why not just a constant?

**Review by phisco — APPROVED** [review]
Looking good, no blocking comments
