### PR TITLE
remove Upbound code from code base

### LINKED ISSUE #6263: `xpkg.upbound` module should be renamed to avoid the appearance of Upbound-specific code in core
### What happened?
The content of the `xpkg.upbound` module was ported from the `up` CLI and not renamed.  It gives the (hopefully incorrect) impression that this code is specific to Upbound functionality.

Since this module is starting to be referenced by other code - see #6262 - it needs to be renamed so that only the upbound-specific functionality, if any, retains the upbound name.  Ideally the code would be generic to any package provider/management system.

### What environment did it happen in?
Crossplane version: 1.18.2

### PR DESCRIPTION
**Pull request by jbw976**
#### Removal of Upbound code

This PR removes all Upbound related code from the Crossplane code base. This is intended to continue improving the project's vendor neutrality positioning in accordance with CNCF guidelines.

A lot of this code came from the fact that `xpkg.upbound.io` was the default registry for a long time and a good experience was built around supporting it smoothly, but that was changed in https://github.com/crossplane/crossplane/pull/6296 in response to feedback on our graduation proposal during due diligence. The Upbound specific code (mostly around `xpkg.upbound.io` auth) is no longer needed anyways, as the standard `docker/login-action` workflow now works well too, as shown in https://github.com/jbw976/function-xbuckets/blob/main/.github/workflows/ci.yml#L174-L192.

So, the biggest change that is functional in nature is completely removing the Upbound modules completely from https://github.com/crossplane/crossplane/tree/main/internal/xpkg/upbound.

I expect zero impact to the community for folks that want to push to `xpkg.upbound.io`, as long as they are using a standard `docker login` --> `crossplane xpkg push` based workflow as shown in the linked workflow above. This very much seems to be the case from my searching for modern conventions across providers, functions, and configurations. It is the recommended path now.

A lot of the other updates are just find/replace in test case strings that made their way into the codebase because everyone was testing with and pulling packages from `xpkg.upbound.io` for years.

Fixes #6263

### How has this change been tested?

I have verified that CI workflows still work fine to push to both `ghcr.io` and (optionally, if the repo maintainer chooses to) `xpkg.upbound.io` using a function build/push workflow shown in https://github.com/jbw976/function-xbuckets/blob/main/.github/workflows/ci.yml. That CI workflow is using the Crossplane CLI built from the changes in this PR (e.g. https://github.com/jbw976/crossplane/tree/bye-up), as shown in https://github.com/jbw976/function-xbuckets/blob/main/.github/workflows/ci.yml#L165-L172. Everything was pushed successfully to all target registries ✅ 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~
- [ ] ~Followed the [API promotion workflow] if this PR introduces, removes, or promotes an API.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet
[API promotion workflow]: https://github.com/crossplane/crossplane/blob/main/contributing/guide-api-promotion.md

### CODE REVIEW

**Comment by jbw976** [comment]
Placing back into draft status while testing the porting of `xpkg batch` to the Crossplane CLI 😇

File: cmd/crank/xpkg/batch.go [hunk 1]
```diff
@@ -0,0 +1,574 @@
+/*
```
Comment (jbw976) [inline cmd/crank/xpkg/batch.go]: This file is mostly all copied from its implementation in the `up` tool. The only differences here are:

* remove upbound context/flags
* use logger instead of pterm to be consistent with rest of crossplane CLI

**Comment by jbw976** [comment]
I have performed testing for the ported `xpkg batch` command as well, so taking this PR out of draft now 🙏

File: cmd/crank/xpkg/batch.go [hunk 2]
```diff
@@ -0,0 +1,575 @@
...
+
+	return nil
+}
+
+// batchCmd builds and pushes a family of Crossplane provider packages.
+type batchCmd struct {
+	fs    afero.Fs
+	fetch fetchFn
+
+	FamilyBaseImage        string   `help:"Family image used as the base for the smaller provider packages."                                                                                                                                       required:""`
```
Comment (negz) [inline cmd/crank/xpkg/batch.go]: Is this CLI tool used by most providers in the ecosystem, or only the big families?

I'm wondering if it really belongs in the `crossplane` CLI, or whether it should be its own distinct CLI tool. Will anyone other than a handful of provider maintainers use it?

File: cmd/crank/xpkg/push.go [hunk 3]
```diff
@@ -122,78 +107,85 @@ func (c *pushCmd) Run(logger logging.Logger) error { //nolint:gocognit // This f
...
 
-	// If there's only one package file, handle the simple path.
-	if len(c.PackageFiles) == 1 {
-		img, err := tarball.ImageFromPath(c.PackageFiles[0], nil)
-		if err != nil {
-			return errors.Wrapf(err, errFmtReadPackage, c.PackageFiles[0])
+	return PushImages(logger, images, c.Package, options)
+}
+
+func PushImages(logger logging.Logger, images []v1.Image, url string, options []remote.Option) error {
```
Comment (negz) [inline cmd/crank/xpkg/push.go]:
```suggestion
func PushImages(logger logging.Logger, images []v1.Image, url string, options ...remote.Option) error {
```

We usually use variadic options.

File: internal/xpkg/build.go [hunk 4]
```diff
@@ -26,6 +26,9 @@ import (
 	v1 "github.com/google/go-containerregistry/pkg/v1"
 	"github.com/google/go-containerregistry/pkg/v1/empty"
 	"github.com/google/go-containerregistry/pkg/v1/mutate"
+	"gopkg.in/yaml.v2"
+	crd "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
```
Comment (negz) [inline internal/xpkg/build.go]: I'd prefer to import this as `apiextensionsv1`. That's the typical pattern we use for API type imports.

File: internal/xpkg/build.go [hunk 5]
```diff
@@ -171,6 +198,42 @@ func (b *Builder) Build(ctx context.Context, opts ...BuildOpt) (v1.Image, runtim
 	case v1beta1.FunctionKind:
 		linter = NewFunctionLinter()
 	case pkgmetav1.ProviderKind:
+		if b.authSource != nil { // if we have an auth.yaml file
+			if p, ok := meta.(metav1.Object); ok {
+				if group, ok := p.GetAnnotations()[AuthMetaAnnotation]; ok {
```
Comment (negz) [inline internal/xpkg/build.go]: This is quite a large block inside a lot of conditionals, which leads to it being quite deeply indented. Could you break this section out into its own function, and use the return early pattern to avoid so much nesting?

File: cmd/crank/xpkg/batch.go (hunk 2 above)
Comment (jbw976) [reply cmd/crank/xpkg/batch.go]: @negz and I chatted about this idea more. We'll explore putting the `batch` functionality into a CLI in the upjet repo, since that is the exclusive audience it's intended to serve. There are a couple tricky parts like how to make the CLI available for provider builds to call it, and how to deal with dependencies on crossplane internal packages (e.g. `/internal/xpkg`, but we'll explore this idea.

I'm going to remove the commit that ports the `xpkg batch` functionality from this PR so we can still make progress on removing Upbound code from the code base without blocking on `xpkg batch`.

**Comment by jbw976** [comment]
This PR is now back to just being focused on removing Upbound code from the code base if folks want to take another look at that smaller scope 😉

**Review by negz — APPROVED** [review]
🎉 Thanks for cleaning this up @jbw976!
